"""Single source of truth for technical-indicator metadata.

Indicator names, descriptions, stockstats column mappings, Alpha Vantage API
mappings and snapshot membership previously lived in three hand-synced copies
(`y_finance.best_ind_params`, `alpha_vantage_indicator.indicator_descriptions`,
and the market analyst's system prompt). Every consumer now reads from this
registry, so adding an indicator is a single ``IndicatorSpec`` entry here:

* ``y_finance.get_stock_stats_indicators_window`` — name validation, stockstats
  column resolution, custom-indicator dispatch, report descriptions.
* ``alpha_vantage_indicator.get_indicator`` — which names the Alpha Vantage API
  can serve and how (function, CSV column, query params).
* ``agents/analysts/market_analyst.py`` — the indicator menu in the system
  prompt is generated by :func:`render_prompt_section`.
* ``market_data_validator`` — the verified-snapshot indicator set comes from
  :func:`snapshot_indicators`.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class IndicatorSpec:
    """Everything the system knows about one technical indicator.

    ``name`` is the canonical, agent-facing identifier and never changes even
    when windows are reconfigured (``rsi`` stays ``rsi`` at window 7).
    """

    name: str
    category: str
    # One-line "Name: ... Usage: ... Tips: ..." text appended to tool output.
    description: str
    # Longer prompt-menu text where it differs from `description` (the tiered
    # multi-timeframe indicators explain their three-tier payload to the agent).
    prompt_description: str | None = None
    # stockstats column computed for this name (None = not a stockstats column).
    stockstats_column: str | None = None
    # Windowed stockstats column form, e.g. "rsi_{window}". None = the window
    # is fixed by stockstats class attributes and cannot be overridden.
    column_template: str | None = None
    default_params: dict = field(default_factory=dict)
    # Dispatch key for indicators computed from OHLCV in stockstats_utils
    # rather than through a stockstats column ("td_9", "z_score", ...).
    custom: str | None = None
    # Alpha Vantage API mapping. av_function None = AV cannot serve this name
    # (the vendor raises so the router falls back to yfinance).
    av_function: str | None = None
    av_column: str | None = None
    av_series_type: bool = True
    av_takes_window: bool = False
    av_fixed_params: dict = field(default_factory=dict)
    # Multiplier applied to stockstats output so all vendors agree on scale
    # (stockstats mfi is 0-1; Alpha Vantage's and the conventional scale is
    # 0-100).
    scale: float = 1.0
    in_snapshot: bool = False
    # Tool-supported names can be kept out of the analyst's prompt menu.
    in_prompt: bool = True


_SPECS = [
    # ---- Moving Averages ------------------------------------------------
    IndicatorSpec(
        name="close_50_sma",
        category="Moving Averages",
        description=(
            "50 SMA: A medium-term trend indicator. "
            "Usage: Identify trend direction and serve as dynamic support/resistance. "
            "Tips: It lags price; combine with faster indicators for timely signals."
        ),
        stockstats_column="close_50_sma",
        column_template="close_{window}_sma",
        default_params={"window": 50},
        av_function="SMA",
        av_column="SMA",
        av_takes_window=True,
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="close_200_sma",
        category="Moving Averages",
        description=(
            "200 SMA: A long-term trend benchmark. "
            "Usage: Confirm overall market trend and identify golden/death cross setups. "
            "Tips: It reacts slowly; best for strategic trend confirmation rather than frequent trading entries."
        ),
        stockstats_column="close_200_sma",
        column_template="close_{window}_sma",
        default_params={"window": 200},
        av_function="SMA",
        av_column="SMA",
        av_takes_window=True,
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="close_10_ema",
        category="Moving Averages",
        description=(
            "10 EMA: A responsive short-term average. "
            "Usage: Capture quick shifts in momentum and potential entry points. "
            "Tips: Prone to noise in choppy markets; use alongside longer averages for filtering false signals."
        ),
        stockstats_column="close_10_ema",
        column_template="close_{window}_ema",
        default_params={"window": 10},
        av_function="EMA",
        av_column="EMA",
        av_takes_window=True,
        in_snapshot=True,
    ),
    # ---- MACD Related ----------------------------------------------------
    IndicatorSpec(
        name="macd",
        category="MACD Related",
        description=(
            "MACD: Computes momentum via differences of EMAs. "
            "Usage: Look for crossovers and divergence as signals of trend changes. "
            "Tips: Confirm with other indicators in low-volatility or sideways markets."
        ),
        stockstats_column="macd",
        av_function="MACD",
        av_column="MACD",
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="macds",
        category="MACD Related",
        description=(
            "MACD Signal: An EMA smoothing of the MACD line. "
            "Usage: Use crossovers with the MACD line to trigger trades. "
            "Tips: Should be part of a broader strategy to avoid false positives."
        ),
        stockstats_column="macds",
        av_function="MACD",
        av_column="MACD_Signal",
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="macdh",
        category="MACD Related",
        description=(
            "MACD Histogram: Shows the gap between the MACD line and its signal. "
            "Usage: Visualize momentum strength and spot divergence early. "
            "Tips: Can be volatile; complement with additional filters in fast-moving markets."
        ),
        stockstats_column="macdh",
        av_function="MACD",
        av_column="MACD_Hist",
        in_snapshot=True,
    ),
    # ---- Momentum Indicators ----------------------------------------------
    IndicatorSpec(
        name="rsi",
        category="Momentum Indicators",
        description=(
            "RSI: Measures momentum to flag overbought/oversold conditions. "
            "Usage: Apply 70/30 thresholds and watch for divergence to signal reversals. "
            "Tips: In strong trends, RSI may remain extreme; always cross-check with trend analysis."
        ),
        stockstats_column="rsi",
        column_template="rsi_{window}",
        default_params={"window": 14},
        av_function="RSI",
        av_column="RSI",
        av_takes_window=True,
        in_snapshot=True,
    ),
    # ---- Stochastic ----------------------------------------------------------
    IndicatorSpec(
        name="stochrsi",
        category="Stochastic",
        description=(
            "StochRSI: A stochastic calculation applied to RSI (14-period, 0-100) that makes overbought/oversold turns more sensitive. "
            "Usage: Readings above 80 flag overbought and below 20 oversold, reacting faster than RSI itself. "
            "Tips: Faster also means noisier — do not pair with rsi (redundant) and confirm signals with a trend or volume indicator."
        ),
        stockstats_column="stochrsi",
        column_template="stochrsi_{window}",
        default_params={"window": 14},
        av_function="STOCHRSI",
        av_column="FastK",
        av_takes_window=True,
    ),
    IndicatorSpec(
        name="kdjk",
        category="Stochastic",
        description=(
            "KDJ %K: The fast stochastic line (9-period) locating the close within the recent high-low range (0-100). "
            "Usage: Readings above 80 flag overbought and below 20 oversold; %K crossing %D triggers entries. "
            "Tips: In strong trends %K can stay pinned at an extreme; confirm with a trend indicator before fading it."
        ),
        stockstats_column="kdjk",
        column_template="kdjk_{window}",
        default_params={"window": 9},
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="kdjd",
        category="Stochastic",
        description=(
            "KDJ %D: The smoothed signal line of %K. "
            "Usage: %K crossing above %D from oversold is a buy trigger; crossing below from overbought a sell trigger. "
            "Tips: Less noisy than %K alone but lags; read together with kdjk rather than in isolation."
        ),
        stockstats_column="kdjd",
        column_template="kdjd_{window}",
        default_params={"window": 9},
    ),
    IndicatorSpec(
        name="kdjj",
        category="Stochastic",
        description=(
            "KDJ %J: The divergence line (3K - 2D) that overshoots %K and %D. "
            "Usage: %J above 100 or below 0 flags stretched conditions earlier than %K or %D. "
            "Tips: Very sensitive — treat extreme %J readings as early warnings, not standalone signals."
        ),
        stockstats_column="kdjj",
        column_template="kdjj_{window}",
        default_params={"window": 9},
    ),
    # ---- Trend Strength --------------------------------------------------------
    IndicatorSpec(
        name="adx",
        category="Trend Strength",
        description=(
            "ADX: Average Directional Index measures trend strength regardless of direction (0-100). "
            "Usage: Readings above 25 confirm a tradable trend; below 20 flags a range-bound market where trend-following signals fail. "
            "Tips: Computed as an EMA-6 smoothing of DX-14 (stockstats), so values differ slightly from the classic Wilder 14/14 ADX on other platforms; combine with pdi/mdi for direction."
        ),
        stockstats_column="adx",
        av_function="ADX",
        av_column="ADX",
        av_series_type=False,
        av_fixed_params={"time_period": "14"},
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="pdi",
        category="Trend Strength",
        description=(
            "+DI: Positive Directional Indicator (14-period) gauges upward pressure. "
            "Usage: pdi above mdi means bulls control the trend; crossovers mark potential trend changes. "
            "Tips: Read together with ADX — a pdi/mdi cross in a low-ADX chop produces false signals."
        ),
        stockstats_column="pdi",
        column_template="pdi_{window}",
        default_params={"window": 14},
        av_function="PLUS_DI",
        av_column="PLUS_DI",
        av_series_type=False,
        av_takes_window=True,
    ),
    IndicatorSpec(
        name="mdi",
        category="Trend Strength",
        description=(
            "-DI: Negative Directional Indicator (14-period) gauges downward pressure. "
            "Usage: mdi above pdi means bears control the trend; crossovers mark potential trend changes. "
            "Tips: Read together with ADX — a cross only matters when ADX confirms a real trend."
        ),
        # stockstats names the negative directional indicator `ndi` (it has no
        # `mdi` handler); the agent-facing name stays the conventional `mdi`.
        stockstats_column="ndi",
        column_template="ndi_{window}",
        default_params={"window": 14},
        av_function="MINUS_DI",
        av_column="MINUS_DI",
        av_series_type=False,
        av_takes_window=True,
    ),
    IndicatorSpec(
        name="supertrend",
        category="Trend Strength",
        description=(
            "SuperTrend (14-period, 3x ATR): A trend-following trailing stop computed on weekly (tier 1), monthly (tier 2) and daily (tier 3) bars. "
            "Usage: Price at or above the line = uptrend with the line as trailing stop; a close through the line flips the trend. Weight a higher tier above a lower one on conflict. "
            "Tips: Computed from OHLCV (not a single stockstats handler); use the distance to the stop for risk sizing and confirm fresh flips with volume or momentum."
        ),
        prompt_description=(
            "SuperTrend (14-period, 3x ATR trailing stop): A trend-following stop-and-reverse line computed on three timeframes at once — weekly (Tier 1, primary), monthly (Tier 2, regime context) and daily (Tier 3, entry timing). "
            "A single supertrend call returns the trend direction, the stop level and the close's distance to it for all three tiers. "
            "Usage: price above the line = uptrend with the line as the trailing stop; a close through the line flips the trend. Report direction and stop for each timeframe. "
            "Tips: when timeframes disagree, weight the higher tier above the lower one (weekly > monthly > daily); use the distance to the stop for risk sizing."
        ),
        custom="supertrend",
        default_params={"window": 14},
    ),
    # ---- Volatility Indicators ---------------------------------------------
    IndicatorSpec(
        name="boll",
        category="Volatility Indicators",
        description=(
            "Bollinger Middle: A 20 SMA serving as the basis for Bollinger Bands. "
            "Usage: Acts as a dynamic benchmark for price movement. "
            "Tips: Combine with the upper and lower bands to effectively spot breakouts or reversals."
        ),
        stockstats_column="boll",
        column_template="boll_{window}",
        default_params={"window": 20},
        av_function="BBANDS",
        av_column="Real Middle Band",
        av_takes_window=True,
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="boll_ub",
        category="Volatility Indicators",
        description=(
            "Bollinger Upper Band: Typically 2 standard deviations above the middle line. "
            "Usage: Signals potential overbought conditions and breakout zones. "
            "Tips: Confirm signals with other tools; prices may ride the band in strong trends."
        ),
        stockstats_column="boll_ub",
        column_template="boll_ub_{window}",
        default_params={"window": 20},
        av_function="BBANDS",
        av_column="Real Upper Band",
        av_takes_window=True,
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="boll_lb",
        category="Volatility Indicators",
        description=(
            "Bollinger Lower Band: Typically 2 standard deviations below the middle line. "
            "Usage: Indicates potential oversold conditions. "
            "Tips: Use additional analysis to avoid false reversal signals."
        ),
        stockstats_column="boll_lb",
        column_template="boll_lb_{window}",
        default_params={"window": 20},
        av_function="BBANDS",
        av_column="Real Lower Band",
        av_takes_window=True,
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="atr",
        category="Volatility Indicators",
        description=(
            "ATR: Averages true range to measure volatility. "
            "Usage: Set stop-loss levels and adjust position sizes based on current market volatility. "
            "Tips: It's a reactive measure, so use it as part of a broader risk management strategy."
        ),
        stockstats_column="atr",
        column_template="atr_{window}",
        default_params={"window": 14},
        av_function="ATR",
        av_column="ATR",
        av_series_type=False,
        av_takes_window=True,
        in_snapshot=True,
    ),
    # ---- Volume-Based Indicators -------------------------------------------
    IndicatorSpec(
        name="vwma",
        category="Volume-Based Indicators",
        description=(
            "VWMA: A moving average weighted by volume. "
            "Usage: Confirm trends by integrating price action with volume data. "
            "Tips: Watch for skewed results from volume spikes; use in combination with other volume analyses."
        ),
        stockstats_column="vwma",
        column_template="vwma_{window}",
        default_params={"window": 14},
    ),
    IndicatorSpec(
        name="mfi",
        category="Volume-Based Indicators",
        description=(
            "MFI: The Money Flow Index is a volume-weighted momentum indicator that measures buying and selling pressure, reported on the conventional 0-100 scale. "
            "Usage: Identify overbought (>80) or oversold (<20) conditions and confirm the strength of trends or reversals. "
            "Tips: Use alongside RSI or MACD to confirm signals; divergence between price and MFI can indicate potential reversals."
        ),
        stockstats_column="mfi",
        column_template="mfi_{window}",
        default_params={"window": 14},
        av_function="MFI",
        av_column="MFI",
        av_series_type=False,
        av_takes_window=True,
        # stockstats computes mfi on a 0-1 scale; every consumer (tool output,
        # verified snapshot, Alpha Vantage) reports the conventional 0-100.
        scale=100.0,
        in_snapshot=True,
    ),
    IndicatorSpec(
        name="obv",
        category="Volume-Based Indicators",
        description=(
            "OBV: On-Balance Volume accumulates signed volume to confirm price moves. "
            "Usage: OBV trending with price confirms the move; divergence between OBV and price warns of weak participation and a possible reversal. "
            "Tips: The absolute level is meaningless — read the slope and divergences against price over the lookback window."
        ),
        custom="obv",
        av_function="OBV",
        av_column="OBV",
        av_series_type=False,
    ),
    # ---- Sequential / Exhaustion ---------------------------------------------
    IndicatorSpec(
        name="td_9",
        category="Sequential / Exhaustion",
        description=(
            "TD-9 (TD Sequential Setup): A DeMark exhaustion indicator computed on weekly (tier 1), monthly (tier 2) and daily (tier 3) bars. "
            "Usage: A running count toward 9 flags an approaching trend exhaustion; a completed 9 is a reversal watch. Weight a higher tier above a lower one on conflict. "
            "Tips: Computed from OHLCV (not a stockstats handler); the count is the live signal, so read counts below 9 as 'approaching', not 'nothing'."
        ),
        prompt_description=(
            "TD-9 (TD Sequential Setup): A DeMark exhaustion/reversal signal computed on three timeframes at once — weekly (Tier 1, primary), monthly (Tier 2, regime context) and daily (Tier 3, entry timing). "
            "A single td_9 call returns the current running count (signed: + buy-setup, - sell-setup) for all three tiers. "
            "Usage: a count climbing toward 9 flags approaching trend exhaustion; a completed 9 is a reversal watch. Report the current count for each timeframe even when below 9. "
            "Tips: when timeframes disagree, weight the higher tier above the lower one (weekly > monthly > daily); a daily 9 does not override a weekly setup still in progress."
        ),
        custom="td_9",
    ),
    # ---- Mean Reversion / Stretch ---------------------------------------------
    IndicatorSpec(
        name="z_score",
        category="Mean Reversion / Stretch",
        description=(
            "Z-Score (20-period close z-score): How many standard deviations the close sits from its 20-period mean, computed on weekly (tier 1), monthly (tier 2) and daily (tier 3) bars. "
            "Usage: A mean-reversion / stretch gauge — |z| >= 2 flags a statistically stretched price (+ overbought, - oversold); near 0 is fair value. Weight a higher tier above a lower one on conflict. "
            "Tips: Computed from OHLCV (not a stockstats handler); a high z-score in a strong trend can persist, so confirm with a trend indicator before fading it."
        ),
        prompt_description=(
            "Z-Score (20-period close z-score): How far the close sits from its 20-period mean, in standard deviations, computed on three timeframes at once — weekly (Tier 1, primary), monthly (Tier 2, regime context) and daily (Tier 3, entry timing). "
            "A single z_score call returns the current reading (signed: + above mean / overbought, - below mean / oversold) for all three tiers. "
            "Usage: |z| >= 2 flags a statistically stretched price and a mean-reversion watch; near 0 is fair value. Report the reading for each timeframe. "
            "Tips: when timeframes disagree, weight the higher tier above the lower one (weekly > monthly > daily); a high z-score in a strong trend can persist, so confirm with a trend indicator before fading it."
        ),
        custom="z_score",
        default_params={"window": 20},
    ),
]

INDICATORS: dict[str, IndicatorSpec] = {spec.name: spec for spec in _SPECS}


def get_spec(name: str) -> IndicatorSpec:
    """Look up an indicator by canonical name; unknown names raise ValueError."""
    spec = INDICATORS.get(name)
    if spec is None:
        raise ValueError(
            f"Indicator {name} is not supported. Please choose from: {list(INDICATORS.keys())}"
        )
    return spec


def supported_names() -> list[str]:
    return list(INDICATORS.keys())


def snapshot_indicators() -> tuple[str, ...]:
    """Indicator names included in the verified market snapshot."""
    return tuple(name for name, spec in INDICATORS.items() if spec.in_snapshot)


def effective_params(name: str, indicator_params: dict | None = None) -> dict:
    """The spec's default params overlaid with any configured overrides.

    ``indicator_params`` maps canonical name -> param overrides (the config's
    ``indicator_params`` key); when None, it is read from the live config.
    Unknown override keys are ignored so a config typo cannot produce a
    malformed stockstats column.
    """
    spec = get_spec(name)
    if indicator_params is None:
        from .config import get_config

        indicator_params = get_config().get("indicator_params") or {}
    params = dict(spec.default_params)
    overrides = indicator_params.get(name) or {}
    params.update({k: v for k, v in overrides.items() if k in params})
    return params


def resolve_column(name: str, params: dict | None = None) -> str:
    """The stockstats column to compute for this name with these params.

    Default params resolve to the bare legacy column (``rsi``, ``boll_ub``) so
    behavior is byte-identical when nothing is configured; overridden params
    resolve through ``column_template`` (``rsi_7``, ``boll_ub_30`` — stockstats
    appends the window suffix to the band names only when a window is given).
    """
    spec = get_spec(name)
    if spec.stockstats_column is None:
        raise ValueError(
            f"Indicator {name} is computed from OHLCV, not as a stockstats column."
        )
    if not spec.column_template or params is None or params == spec.default_params:
        return spec.stockstats_column
    return spec.column_template.format(**params)


def render_prompt_section() -> str:
    """The category-grouped indicator menu for the market analyst's prompt."""
    by_category: dict[str, list[IndicatorSpec]] = {}
    for spec in INDICATORS.values():
        if spec.in_prompt:
            by_category.setdefault(spec.category, []).append(spec)

    blocks = []
    for category, specs in by_category.items():
        lines = [f"{category}:"]
        for spec in specs:
            lines.append(f"- {spec.name}: {spec.prompt_description or spec.description}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)
