from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    # ``company_of_interest`` carries the Kalshi contract identifier for
    # the analysis window (e.g. ``KXBTCD-26MAY05-T100000``). The field name
    # is preserved so the existing graph wiring keeps working until Phase 4
    # introduces dedicated contract-aware naming.
    company_of_interest: Annotated[str, "Kalshi contract id under analysis"]
    trade_date: Annotated[str, "Decision date for the contract (yyyy-mm-dd)"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst (technicals)"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst (Reddit + CMC)"]
    news_report: Annotated[str, "Report from the News Analyst (crypto news + macro)"]
    on_chain_report: Annotated[str, "Report from the On-chain Analyst (chain flows, ETF custody)"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the YES-vs-NO mispricing debate"
    ]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on Kelly stake size given confidence"
    ]
    final_trade_decision: Annotated[str, "Final MarketDecision from the Portfolio Manager"]
    past_context: Annotated[str, "Memory log context injected at run start (same-contract decisions + cross-contract lessons)"]
