from typing import Annotated, Literal, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # ----------------------------------------------------------------------
    # Polymarket Phase A additions
    # ----------------------------------------------------------------------
    # `instrument_type` is the discriminator. Existing callers default to
    # 'stock' so behavior is unchanged. Polymarket callers (via
    # propagate_market) set it to 'polymarket' and populate the optional
    # fields below. Analysts and conditional_logic branch on this field.
    instrument_type: Annotated[
        Literal["stock", "polymarket"],
        "Discriminator: which kind of instrument is being analysed",
    ]
    market_id: Annotated[
        Optional[str],
        "Polymarket market id (gamma-api `id`). None in stock mode.",
    ]
    market_question: Annotated[
        Optional[str],
        "Polymarket question text. None in stock mode.",
    ]
    yes_price: Annotated[
        Optional[float],
        "Current YES contract price in [0.0, 1.0]. None in stock mode.",
    ]
    resolution_date: Annotated[
        Optional[str],
        "ISO 8601 resolution date for the prediction market. None in stock mode.",
    ]
    probability_report: Annotated[
        Optional[str],
        "Probability analyst's report (replaces fundamentals_report semantically "
        "in polymarket mode). None in stock mode.",
    ]
