"""Build an MkDocs Material site under ``docs/`` from completed runs.

Each run lives at ``docs/<TICKER>/<DATE>_<MODEL>_<TS>/complete_report.md``.

Layout produced by this script:

* ``docs/index.md`` -- home page with daily decision summaries, ticker
  list, and regeneration instructions.
* ``docs/<TICKER>/index.md`` -- per-ticker hub page with a table of runs.

MkDocs auto-discovers files for navigation, so per-file front matter is
not required and is stripped from each ``complete_report.md`` if present
(legacy Jekyll/just-the-docs migration).

Run the full local workflow:

    python scripts/report_workflow.py

Idempotent: rewrites ``docs/index.md``, ``docs/<TICKER>/index.md``, and
strips Jekyll front matter from each ``complete_report.md`` in place.

Note: ``docs/index.md`` and the per-ticker ``index.md`` hubs are derived
artifacts and are gitignored. They are regenerated by
``scripts/report_workflow.py`` from the committed stage files; do not commit
them. Only the raw stage files under each run folder are the tracked source of
truth.
"""
from __future__ import annotations

import argparse
import contextlib
import math
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from cli.report_fields import extract_price_target, field, parse_money  # noqa: E402

DOCS_DIR = REPO_ROOT / "docs"

TICKER_DIR_RE = re.compile(r"^[A-Za-z0-9.\-]+$")
NON_TICKER_DIRS = {"archive", "assets", "stylesheets"}

# Run folder name is <DATE>_<MODEL>[_<RUN_DATE>_<RUN_TIME>]. The optional
# RUN_DATE/RUN_TIME tail records when the run started (vs. the analysis
# date). MODEL is non-greedy so it doesn't swallow the trailing timestamp.
RUN_DIR_RE = re.compile(
    r"^(?P<date>\d{8})_(?P<model>.+?)"
    r"(?:_(?P<run_date>\d{8})_(?P<run_time>\d{6}))?$"
)

DISCLAIMER = (
    "!!! warning \"Disclaimer\"\n"
    "    This website and its AI-generated reports are for **AI testing and "
    "experimentation only**. They do not constitute financial or investment "
    "advice and are not a substitute for a qualified financial adviser. "
    "Reports may contain errors. Do not use them to make investment or "
    "trading decisions."
)

FRONT_MATTER_RE = re.compile(r"\A---\n.*?\n---\n+", re.DOTALL)


class Run(NamedTuple):
    ticker: str
    analysis_date: str   # YYYY-MM-DD
    model: str
    run_started: str     # YYYY-MM-DD HH:MM:SS
    folder_name: str     # used in URLs


class SummaryRow(NamedTuple):
    ticker: str
    model: str
    report_link: str
    rating: str
    action: str
    current_price: float | None
    price_target: float | None
    target_uplift: float | None
    annualized_uplift: float | None
    confidence: str
    horizon: str


class DailySummary(NamedTuple):
    analysis_date: str
    rows: list[SummaryRow]
    incomplete_count: int = 0


def parse_run_folder(ticker_dir: Path, run_path: Path) -> Run | None:
    """Parse ``docs/<TICKER>/<RUN>``; ticker comes from the parent dir."""
    if not run_path.is_dir():
        return None
    m = RUN_DIR_RE.match(run_path.name)
    if not m:
        return None
    date = m.group("date")
    analysis_date = f"{date[:4]}-{date[4:6]}-{date[6:8]}"
    rd, rt = m.group("run_date"), m.group("run_time")
    if rd and rt:
        run_started = f"{rd[:4]}-{rd[4:6]}-{rd[6:8]} {rt[:2]}:{rt[2:4]}:{rt[4:6]}"
    else:
        run_started = datetime.fromtimestamp(run_path.stat().st_mtime).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    return Run(
        ticker=ticker_dir.name.upper(),
        analysis_date=analysis_date,
        model=m.group("model"),
        run_started=run_started,
        folder_name=run_path.name,
    )


def read_text(path: Path) -> str:
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def extract_time_horizon(decision_text: str) -> str:
    horizon = field(decision_text, "Time Horizon")
    if horizon:
        return horizon
    m = re.search(r"within\s+~?(\d+)\s+days", decision_text, flags=re.I)
    if m:
        return f"{m.group(1)}d"
    return ""


def normalize_analysis_date(value: str | None) -> str | None:
    if value is None:
        return None
    value = value.strip()
    if re.fullmatch(r"\d{8}", value):
        return f"{value[:4]}-{value[4:6]}-{value[6:8]}"
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        return value
    raise ValueError("analysis date must use YYYYMMDD or YYYY-MM-DD")


CURRENT_PRICE_PATTERNS = [
    r"closed\s+Friday,\s*\*\*\d{4}-\d{2}-\d{2}\s+at\s+\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Most recent close[^$\n]*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Latest close[^$\n]*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Latest trading day[^\n$]*(?:Last close|close)\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"last trading day[^\n$]*close\s+\$([0-9][0-9,]*(?:\.\d+)?)",
    r"\*\*Last Close\s*\([^)]*\):\*\*\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"\*\*Last Close:\*\*\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Last Close\s*:?\s*\*+\$([0-9][0-9,]*(?:\.\d+)?)\*+",
    r"Last Close\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"\*\*Last close:\*\*\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Last close\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"\|\s*\*{0,2}Close Price\*{0,2}\s*\|\s*\*{0,2}\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Current close\s*\([^)]*\)\*{0,2}\s*:?\s*\*{0,2}\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Close\s*\(5/29\)\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"ending\s+the\s+week\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"(?:close|closing)\s+of\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closed\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closing\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closed\s+May\s+29\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"to\s+\$([0-9][0-9,]*(?:\.\d+)?)\s+close\s+on\s+\d{4}-\d{2}-\d{2}",
    r"recent close is\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"May\s+29,\s+\d{4}:\*\*\s+[^\n]*?closing\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29:\*\*\s+[^\n]*?close\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29\)\s+closed\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29\s+close\s+\(\$([0-9][0-9,]*(?:\.\d+)?)\)",
    r"last\s+printing\s+a\s+close\s+of\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-05-29",
    r"5/29\s+\(price\s+down[^$]*\$([0-9][0-9,]*(?:\.\d+)?)\)",
    r"then\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closing\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closing\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-\d{2}-\d{2}",
    r"closed\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-\d{2}-\d{2}",
    r"closed\s+\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-\d{2}-\d{2}",
    r"Close\s+rose\s+from[^\n]+?to\s+\*\*\$?([0-9][0-9,]*(?:\.\d+)?)\s+\(May\s+29\)",
    r"Close\s+\$[0-9][0-9,]*(?:\.\d+)?[^\n]+?→\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"closing\s+\*\*([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"new\s+high\s+\(([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29\)",
    r"\|\s*\d{4}-05-29\s*\|\s*\*\*\$([0-9][0-9,]*(?:\.\d+)?)\*\*",
    r"\|\s*Close\s*\|\s*\*?\*?\$([0-9][0-9,]*(?:\.\d+)?)\*?\*?",
]

CURRENT_PRICE_FALLBACK_PATTERNS = [
    r"near\s+current\s+~?\$([0-9][0-9,]*(?:\.\d+)?)\b",
    r"current\s+~?\$([0-9][0-9,]*(?:\.\d+)?)\s+(?:strength|level|levels|print)",
]


def extract_current_price(
    report_text: str, decision_text: str, trader_text: str,
    analysis_date: str | None = None,
) -> float | None:
    # Current means the report-time latest close, not a live quote.
    decision_value = field(decision_text, "Current Price")
    if decision_value and decision_value.lower() != "not provided":
        return parse_money(decision_value)

    market_text = re.split(
        r"^### (?:Sentiment|News|Fundamentals) Analyst\b|^## II\.",
        report_text, maxsplit=1, flags=re.M,
    )[0][:35000]
    canonical = parse_money(field(market_text, "Current Price"))
    if canonical is not None:
        return canonical
    plain = market_text.replace("**", "").replace("`", "")

    def date_is_relevant(match: re.Match, source: str) -> bool:
        if not analysis_date:
            return True
        line_start = source.rfind("\n", 0, match.start()) + 1
        # Match the date attached to the quote, not a later earnings/catalyst
        # mentioned in the same line. Preserve comma-separated OHLCV numbers.
        prefix = source[line_start:match.start(1)]
        suffix = source[match.end(1):].split("\n", 1)[0]
        suffix = re.split(r",(?!\s*\d{4}\b)|[;!?]|\.(?!\d)", suffix, maxsplit=1)[0]
        context = prefix + match.group(1) + suffix
        months = r"(January|February|March|April|May|June|July|August|September|October|November|December)"
        quote_context = source[match.start():match.end(1)] + suffix
        # An explicit quote date takes precedence over an unrelated date
        # before the matched close (for example an upcoming earnings event).
        if re.search(rf"\b(?:\d{{4}}-\d{{2}}-\d{{2}}|{months}\s+\d{{1,2}}\b)", quote_context, flags=re.I):
            context = quote_context
        dates = re.findall(r"\b\d{4}-\d{2}-\d{2}\b", context)
        for natural_date in re.finditer(
            rf"\b{months}\s+(\d{{1,2}})(?:(?:,\s*|\s+)(\d{{4}}))?\b", context, flags=re.I,
        ):
            year = natural_date.group(3) or normalize_analysis_date(analysis_date)[:4]
            try:
                dates.append(datetime.strptime(
                    f"{natural_date.group(1)} {natural_date.group(2)} {year}", "%B %d %Y"
                ).strftime("%Y-%m-%d"))
            except ValueError:
                return False
        if not dates:
            return True
        try:
            for candidate in dates:
                datetime.strptime(candidate, "%Y-%m-%d")
        except ValueError:
            return False
        date = normalize_analysis_date(analysis_date)
        if re.search(r"\b(?:latest|last|current|most recent)\b", context, flags=re.I):
            # The latest close can precede the analysis date (weekends, market
            # hours, holidays); it cannot come from a future session.
            return all(candidate <= date for candidate in dates)
        return all(candidate == date for candidate in dates)

    def parse_candidate(match: re.Match, source: str) -> float | None:
        line_end = source.find("\n", match.end(1))
        value = source[match.start(1):line_end if line_end >= 0 else len(source)]
        return parse_money(value.replace("`", ""))

    # Keep the whole quote token: validating only the captured numeric prefix
    # would turn a date, percentage or range into an apparent closing price.
    number = (
        r"((?:[$€£¥]\s*)?[0-9][0-9,]*(?:\.\d+)?)\b"
        r"(?!\d|[.,]\d|\s*%|\s*(?:[-–—/]|to\b)\s*(?:[$€£¥]\s*)?\d)"
    )
    # Prefer explicit latest/verified evidence over historical price examples.
    for pattern in (
        rf"\b(?:latest|last|current|most recent)(?:\s+verified)?\s+close(?:\s+price)?\s*(?:was|is|of|at|:)\s*{number}",
        rf"\bverified[^\n]{{0,80}}?\bclose\s*(?:was|is|of|at|:)\s*{number}",
        rf"\b(?:latest|verified)[^\n]{{0,160}}?\bclosed?\s+(?:at\s+)?{number}",
        rf"\bverified[^\n]{{0,100}}?\bO\s+[\d.,]+,\s*H\s+[\d.,]+,\s*L\s+[\d.,]+,\s*C\s+{number}",
        rf"^[ \t]*(?:[-*][ \t]+)?(?:Last )?Close(?: Price)?\s*:\s*{number}",
        rf"^\|\s*(?:Last |Current )?Close(?: Price)?\s*\|\s*{number}",
    ):
        for match in re.finditer(pattern, plain, flags=re.I | re.M):
            if not date_is_relevant(match, plain):
                continue
            token = match.group(1)
            # A bare year is ambiguous in prose. Canonical Current Price
            # fields and prices with a currency/decimal remain unambiguous.
            if re.fullmatch(r"(?:19|20|21)\d{2}", token):
                continue
            price = parse_candidate(match, plain)
            if price is not None:
                return price
    if analysis_date:
        date = datetime.strptime(normalize_analysis_date(analysis_date), "%Y-%m-%d")
        # Natural-language dates often omit the year in the latest session.
        day = rf"(?:{date:%Y-%m-%d}|{date:%B}\s+{date.day}(?:,?\s+{date.year})?(?!\d|,?\s+\d{{4}}))"
        for pattern in (
            rf"\bclosed?\s+(?:at\s+)?{number}\s+on\s+{day}",
            rf"\b{day}[^\n]{{0,180}}?\bclosed?\s*(?:was|is|at|:)\s*{number}",
        ):
            for match in re.finditer(pattern, plain, flags=re.I):
                price = parse_candidate(match, plain)
                if price is not None:
                    return price
    for pattern in CURRENT_PRICE_PATTERNS:
        # These legacy patterns were introduced for a May 29 report batch.
        # They must not promote those historical examples in later reports.
        if (analysis_date and ("May" in pattern or "5/29" in pattern or "05-29" in pattern)
                and normalize_analysis_date(analysis_date)[5:] != "05-29"):
            continue
        for m in re.finditer(pattern, market_text, flags=re.I):
            if not date_is_relevant(m, market_text):
                continue
            price = parse_candidate(m, market_text)
            if price is not None:
                return price
    decision_and_trader = f"{decision_text}\n{trader_text}"
    for pattern in CURRENT_PRICE_FALLBACK_PATTERNS:
        for m in re.finditer(pattern, decision_and_trader, flags=re.I):
            price = parse_candidate(m, decision_and_trader)
            if price is not None:
                return price
    # An entry price is a proposed execution level, not the observed close.
    return None


def extract_confidence(report_text: str) -> str:
    value = field(report_text, "Confidence")
    if value.lower() in {"low", "medium", "high"}:
        return value.capitalize()
    for pattern in (
        r"^\*\*Confidence:\*\*\s*([A-Za-z]+)",
        r"Confidence is \*\*([A-Za-z]+)\*\*",
        r"Confidence:\s*([A-Za-z]+)",
    ):
        m = re.search(pattern, report_text, flags=re.I | re.M)
        if m and m.group(1).lower() in {"low", "medium", "high"}:
            return m.group(1).capitalize()
    return "n/a"


def horizon_months(horizon: str) -> float | None:
    h = horizon.lower().replace("–", "-").replace("—", "-")
    if "4 quarters" in h:
        return 12.0
    if re.search(r"\bthrough\s+q[1-4]\s+\d{4}\s+earnings\b", h):
        return 3.0
    m = re.search(r"(\d+)\s*\+\s*(?:m\b|months?\b)", h)
    if m:
        return float(m.group(1))
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*days?", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) / 30.4375
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*d\b", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) / 30.4375
    m = re.search(r"(\d+)\s*d\b", h)
    if m:
        return float(m.group(1)) / 30.4375
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*weeks?", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) * 12.0 / 52.0
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*w\b", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) * 12.0 / 52.0
    m = re.search(r"(\d+)\s*w\b", h)
    if m:
        return float(m.group(1)) * 12.0 / 52.0
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*quarters?", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) * 3.0
    m = re.search(r"(\d+)\s*quarters?", h)
    if m:
        return float(m.group(1)) * 3.0
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*months?", h)
    if m:
        return (float(m.group(1)) + float(m.group(2))) / 2.0
    m = re.search(r"(\d+)\s*months?", h)
    if m:
        return float(m.group(1))
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*m\b", h)
    if m:
        return (float(m.group(1)) + float(m.group(2))) / 2.0
    m = re.search(r"(\d+)\s*m\b", h)
    if m:
        return float(m.group(1))
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*years?", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) * 12.0
    m = re.search(r"(\d+)\s*years?", h)
    if m:
        return float(m.group(1)) * 12.0
    return None


def build_summary_row(run: Run) -> SummaryRow:
    run_dir = DOCS_DIR / run.ticker / run.folder_name
    decision_text = read_text(run_dir / "5_portfolio" / "decision.md")
    trader_text = read_text(run_dir / "3_trading" / "trader.md")
    report_text = read_text(run_dir / "complete_report.md")

    current = extract_current_price(report_text, decision_text, trader_text, run.analysis_date)
    target = extract_price_target(decision_text)
    horizon = extract_time_horizon(decision_text)
    confidence = extract_confidence(decision_text)
    if confidence == "n/a":
        confidence = extract_confidence(report_text)
    target_uplift = None
    annualized_uplift = None
    if current is not None and target is not None and current != 0:
        target_uplift = target / current - 1.0
        months = horizon_months(horizon)
        if months and months > 0 and 1.0 + target_uplift > 0:
            annualized_uplift = math.pow(1.0 + target_uplift, 12.0 / months) - 1.0

    return SummaryRow(
        ticker=run.ticker,
        model=run.model,
        report_link=f"./{run.ticker}/{run.folder_name}/complete_report.md",
        rating=field(decision_text, "Rating") or "n/a",
        action=field(trader_text, "Action") or "n/a",
        current_price=current,
        price_target=target,
        target_uplift=target_uplift,
        annualized_uplift=annualized_uplift,
        confidence=confidence,
        horizon=horizon or "n/a",
    )


def latest_runs(
    by_ticker: dict[str, list[Run]], analysis_date: str | None = None
) -> list[Run]:
    """Return the newest run per ticker/model pair.

    The homepage should include parallel model evaluations for the same
    ticker and analysis date, while still collapsing reruns of the same
    ticker/model to the newest run-start timestamp.
    """
    analysis_date = normalize_analysis_date(analysis_date)
    latest_by_ticker_model: dict[tuple[str, str], Run] = {}
    for ticker_runs in by_ticker.values():
        if analysis_date:
            ticker_runs = [r for r in ticker_runs if r.analysis_date == analysis_date]
        for run in ticker_runs:
            key = (run.ticker, run.model)
            existing = latest_by_ticker_model.get(key)
            if existing is None or (run.analysis_date, run.run_started) > (
                existing.analysis_date,
                existing.run_started,
            ):
                latest_by_ticker_model[key] = run
    return sorted(
        latest_by_ticker_model.values(),
        key=lambda r: (r.ticker, r.model),
    )


def analysis_dates(by_ticker: dict[str, list[Run]]) -> list[str]:
    dates = {run.analysis_date for ticker_runs in by_ticker.values() for run in ticker_runs}
    return sorted(dates, reverse=True)


def build_daily_summaries(by_ticker: dict[str, list[Run]]) -> list[DailySummary]:
    summaries = []
    for analysis_date in analysis_dates(by_ticker):
        runs = latest_runs(by_ticker, analysis_date)
        if runs:
            rows = [build_summary_row(run) for run in runs]
            complete = [row for row in rows if row.price_target is not None]
            summaries.append(
                DailySummary(
                    analysis_date=analysis_date,
                    rows=complete,
                    incomplete_count=len(rows) - len(complete),
                )
            )
    return summaries


def summary_sort_key(row: SummaryRow) -> tuple[str, str]:
    return (row.ticker, row.model)


SUMMARY_PLACEHOLDERS = frozenset({
    "", "n/a", "na", "none", "null", "unknown", "not provided", "not available",
    "no verified close", "no target set", "not calculated", "no numeric horizon",
    "not assessed", "not specified", "not rated", "no action stated",
})


def summary_text(value: str, missing: str) -> str:
    return missing if value.strip().lower() in SUMMARY_PLACEHOLDERS else value


def format_price(value: float | None, missing: str = "Not provided") -> str:
    if value is None:
        return missing
    if 0 < value < 0.01:
        return f"${value:.8g}"
    if value >= 1000:
        return f"${value:,.0f}"
    if value >= 100:
        return f"${value:,.2f}"
    return f"${value:.2f}"


def format_percent(value: float | None, missing: str = "Not calculated") -> str:
    if value is None:
        return missing
    return f"{value * 100:+.1f}%"


def short_horizon(horizon: str) -> str:
    return (
        horizon.replace(" months", "m")
        .replace(" month", "m")
        .replace(" weeks", "w")
        .replace(" week", "w")
        .replace(" days", "d")
        .replace(" day", "d")
    )


def decision_summary_anchor(analysis_date: str) -> str:
    return f"{analysis_date}-decision-summary"


def build_decision_summary(
    rows: list[SummaryRow], analysis_date: str | None = None
) -> list[str]:
    analysis_date = normalize_analysis_date(analysis_date)
    heading = (
        f"## {analysis_date} Decision Summary"
        if analysis_date
        else "## Latest Decision Summary"
    )
    note = (
        f"_Uses the latest {analysis_date} run folder for each ticker/model pair. Current price is the report-time latest close parsed from the report, not a live quote. Target uplift is target/current − 1. Unprovided values are labeled explicitly; uplift requires a numeric target and verified close, and 1Y uplift also requires a numeric horizon. Confidence uses the final decision when supplied, otherwise the report's confidence. 1Y uplift is annualized from the midpoint of the stated horizon, so short-horizon rows can look extreme._"
        if analysis_date
        else "_Uses the latest run folder for each ticker/model pair. Current price is the report-time latest close parsed from the report, not a live quote. Target uplift is target/current − 1. Unprovided values are labeled explicitly; uplift requires a numeric target and verified close, and 1Y uplift also requires a numeric horizon. Confidence uses the final decision when supplied, otherwise the report's confidence. 1Y uplift is annualized from the midpoint of the stated horizon, so short-horizon rows can look extreme._"
    )
    lines = [
        heading,
        "",
        note,
        "",
        "| Ticker | Model | Suggestion | Current | Target | Target uplift | 1Y uplift | Confidence | Horizon |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for row in sorted(rows, key=summary_sort_key):
        suggestion = f"{summary_text(row.action, 'No action stated')} / {summary_text(row.rating, 'Not rated')}"
        uplift_missing = "No target set" if row.price_target is None else "No verified close"
        annualized_missing = uplift_missing if row.target_uplift is None else "No numeric horizon"
        lines.append(
            f"| [{row.ticker}]({row.report_link}) | `{row.model}` | {suggestion} | "
            f"{format_price(row.current_price, 'No verified close')} | {format_price(row.price_target, 'No target set')} | "
            f"{format_percent(row.target_uplift, uplift_missing)} | {format_percent(row.annualized_uplift, annualized_missing)} | "
            f"{summary_text(row.confidence, 'Not assessed')} | {short_horizon(summary_text(row.horizon, 'Not specified'))} |"
        )
    lines.append("")
    return lines


def build_daily_decision_summaries(
    summaries: list[DailySummary],
    focus_analysis_date: str | None = None,
) -> list[str]:
    focus_analysis_date = normalize_analysis_date(focus_analysis_date)
    lines = [
        "## Daily Decision Summaries",
        "",
        '<div class="daily-summary-layout" markdown="1">',
        "",
        '<nav class="daily-summary-rail" aria-label="Analysis dates">',
        "<h3>Dates</h3>",
        "<ul>",
    ]
    for summary in summaries:
        report_count = len(summary.rows)
        suffix = "report" if report_count == 1 else "reports"
        classes = ["daily-summary-date"]
        if focus_analysis_date == summary.analysis_date:
            classes.append("daily-summary-date--active")
        lines.extend(
            [
                "<li>",
                (
                    f'<a class="{" ".join(classes)}" '
                    f'href="#{decision_summary_anchor(summary.analysis_date)}">'
                    f"{summary.analysis_date}</a>"
                ),
                f"<span>{report_count} {suffix}</span>",
                "</li>",
            ]
        )
    lines.extend(
        [
            "</ul>",
            "</nav>",
            "",
            '<div class="daily-summary-tables" markdown="1">',
            "",
        ]
    )
    for summary in summaries:
        lines.extend(build_decision_summary(summary.rows, summary.analysis_date))
        if summary.incomplete_count:
            lines.extend([
                f"_{summary.incomplete_count} incomplete decision(s) excluded: a supported numeric price target is required._",
                "",
            ])
    lines.extend(
        [
            "</div>",
            "",
            "</div>",
            "",
        ]
    )
    return lines


def build_regeneration_skill() -> list[str]:
    return [
        "## Regeneration Skill",
        "",
        "When ticker folders are upgraded with newer report data, regenerate this homepage instead of editing the table by hand:",
        "",
        "1. Add each completed run under `docs/<TICKER>/<YYYYMMDD>_<MODEL>_<YYYYMMDD>_<HHMMSS>/` with `complete_report.md`, `3_trading/trader.md`, and `5_portfolio/decision.md` present.",
        "2. Run `python scripts/report_workflow.py --analysis-date YYYYMMDD` from the repository root.",
        "3. Review `docs/index.md` and the affected `docs/<TICKER>/index.md` files in `git diff`.",
        "4. If a row has a missing value, check that the new report includes `**Rating**`, `**Current Price**`, `**Price Target**`, `**Time Horizon**`, and `**Action**`.",
        "",
        "The generator groups summaries by analysis date and chooses the newest run per ticker/model pair by run-start timestamp within each date.",
        "",
    ]


def build_home(
    by_ticker: dict[str, list[Run]],
    total_runs: int,
    daily_summaries: list[DailySummary],
    focus_analysis_date: str | None = None,
) -> str:
    tickers = sorted(by_ticker)
    lines = [
        "# TradingAgents Reports",
        "",
        f"_{total_runs} runs across {len(tickers)} tickers._",
        "",
        DISCLAIMER,
        "",
        "Part of [Everyday Financial Planning at Altair](https://altairworld.com/services/financial-planning).",
        "",
        *build_daily_decision_summaries(daily_summaries, focus_analysis_date),
        *build_regeneration_skill(),
        "## Tickers",
        "",
    ]
    for ticker in tickers:
        n = len(by_ticker[ticker])
        suffix = "run" if n == 1 else "runs"
        lines.append(f"- [{ticker}]({ticker}/index.md) &middot; {n} {suffix}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def replace_decision_summary(home_text: str, summary_lines: list[str]) -> str:
    new_summary = "\n".join(summary_lines).rstrip() + "\n\n"
    patterns = [
        re.compile(
            r"^## Daily Decision Summaries\n.*?(?=^## Regeneration Skill\n)",
            flags=re.M | re.S,
        ),
        re.compile(
            r"^## .+Decision Summary\n.*?(?=^## Regeneration Skill\n)",
            flags=re.M | re.S,
        ),
    ]
    for pattern in patterns:
        new_text, replacements = pattern.subn(new_summary, home_text, count=1)
        if replacements == 1:
            return new_text
    raise ValueError("Could not find decision summary block in docs/index.md")


def build_ticker_hub(ticker: str, runs: list[Run]) -> str:
    runs_sorted = sorted(
        runs,
        key=lambda r: (r.analysis_date, r.run_started),
        reverse=True,
    )
    lines = [
        f"# {ticker}",
        "",
        f"_{len(runs_sorted)} run(s)._",
        "",
        "| Analysis date | Model | Run started | Report |",
        "| --- | --- | --- | --- |",
    ]
    for r in runs_sorted:
        link = f"./{r.folder_name}/complete_report.md"
        lines.append(
            f"| {r.analysis_date} | `{r.model}` | {r.run_started} | "
            f"[Open]({link}) |"
        )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def remove_stale_ticker_hubs(active_tickers: set[str]) -> int:
    removed = 0
    for ticker_dir in sorted(DOCS_DIR.iterdir()):
        if not ticker_dir.is_dir():
            continue
        if ticker_dir.name in NON_TICKER_DIRS:
            continue
        if not TICKER_DIR_RE.match(ticker_dir.name):
            continue
        if ticker_dir.name.upper() in active_tickers:
            continue

        hub_path = ticker_dir / "index.md"
        if hub_path.is_file():
            hub_path.unlink()
            removed += 1

        with contextlib.suppress(OSError):
            ticker_dir.rmdir()

    return removed


def strip_legacy_front_matter(run: Run) -> bool:
    """Drop any legacy Jekyll/just-the-docs front matter from a run report."""
    path = DOCS_DIR / run.ticker / run.folder_name / "complete_report.md"
    if not path.is_file():
        return False
    body = path.read_text(encoding="utf-8")
    new_body = FRONT_MATTER_RE.sub("", body, count=1)
    if new_body == body:
        return False
    path.write_text(new_body, encoding="utf-8")
    return True


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary-analysis-date",
        help="Focus this analysis date in the homepage decision summaries.",
    )
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Rewrite only the daily decision-summary block in docs/index.md.",
    )
    args = parser.parse_args(argv)
    try:
        args.summary_analysis_date = normalize_analysis_date(args.summary_analysis_date)
    except ValueError as exc:
        parser.error(str(exc))
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not DOCS_DIR.is_dir():
        print(f"docs/ not found at {DOCS_DIR}", file=sys.stderr)
        return 1

    runs: list[Run] = []
    for ticker_dir in sorted(DOCS_DIR.iterdir()):
        if not ticker_dir.is_dir():
            continue
        if not TICKER_DIR_RE.match(ticker_dir.name):
            continue
        if ticker_dir.name == "assets":
            continue
        for run_dir in sorted(ticker_dir.iterdir()):
            run = parse_run_folder(ticker_dir, run_dir)
            if run is None:
                continue
            runs.append(run)

    if not runs:
        print("No run folders found under docs/.", file=sys.stderr)
        return 1

    by_ticker: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        by_ticker[r.ticker].append(r)
    removed_stale_hubs = remove_stale_ticker_hubs(set(by_ticker))

    daily_summaries = build_daily_summaries(by_ticker)
    if not daily_summaries:
        print("No runs available for homepage summaries.", file=sys.stderr)
        return 1
    summary_dates = {summary.analysis_date for summary in daily_summaries}
    if args.summary_analysis_date and args.summary_analysis_date not in summary_dates:
        print(
            f"No run folders found for analysis date {args.summary_analysis_date}.",
            file=sys.stderr,
        )
        return 1

    if args.summary_only:
        index_path = DOCS_DIR / "index.md"
        try:
            index_path.write_text(
                replace_decision_summary(
                    read_text(index_path),
                    build_daily_decision_summaries(
                        daily_summaries,
                        args.summary_analysis_date,
                    ),
                ),
                encoding="utf-8",
            )
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 1
        focus = args.summary_analysis_date or "latest"
        print(f"Wrote docs/index.md daily decision summaries; focus={focus}.")
        return 0

    (DOCS_DIR / "index.md").write_text(
        build_home(
            by_ticker,
            total_runs=len(runs),
            daily_summaries=daily_summaries,
            focus_analysis_date=args.summary_analysis_date,
        ),
        encoding="utf-8",
    )

    for ticker in sorted(by_ticker):
        hub_path = DOCS_DIR / ticker / "index.md"
        hub_path.parent.mkdir(parents=True, exist_ok=True)
        hub_path.write_text(
            build_ticker_hub(ticker, by_ticker[ticker]),
            encoding="utf-8",
        )

    rewritten = 0
    for r in runs:
        if strip_legacy_front_matter(r):
            rewritten += 1

    print(
        f"Wrote docs/index.md, {len(by_ticker)} ticker hubs, and stripped "
        f"legacy front matter from {rewritten} of {len(runs)} run reports. "
        f"Removed {removed_stale_hubs} stale ticker hub(s)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
