"""Render every run under docs/ into a single docs/index.html for GitHub Pages.

Folder layout produced:

    docs/
        index.html                                       ← single Pages entry
        .nojekyll                                        ← serve raw, skip Jekyll
        <TICKER>_<DATE>_<MODEL>_<TS>/
            complete_report.md   (kept, source of truth)
            1_analysts/, ...     (kept)

The page has a sticky TOC grouped by ticker plus one collapsed
``<details>`` block per run (browser-native, no JS). Pages source:
main + /docs. URL: https://<user>.github.io/<repo>/

Run locally:

    python scripts/build_reports_site.py

The script is idempotent — re-running rewrites docs/index.html in place.
"""

from __future__ import annotations

import html
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import NamedTuple

try:
    import markdown  # type: ignore
except ImportError:
    markdown = None


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

RUN_DIR_RE = re.compile(
    r"^(?P<ticker>[A-Za-z0-9.\-]+)_(?P<date>\d{8})_(?P<model>.+?)"
    r"(?:_(?P<run_date>\d{8})_(?P<run_time>\d{6}))?$"
)

PAGE_CSS = """
:root { color-scheme: light dark; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 960px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6;
}
h1, h2, h3, h4 { line-height: 1.3; }
h2 { margin-top: 2.4rem; padding-top: .4rem; border-top: 1px solid rgba(127,127,127,.25); }
table { border-collapse: collapse; width: 100%; margin: .8rem 0; }
th, td { border: 1px solid rgba(127,127,127,.4); padding: .4rem .6rem; text-align: left; }
code { background: rgba(127,127,127,.15); padding: .1rem .3rem; border-radius: 3px; }
pre { background: rgba(127,127,127,.1); padding: .8rem; overflow-x: auto; border-radius: 6px; }
.muted { opacity: .65; font-size: .9rem; }
.disclaimer {
  border-left: 3px solid #d77; background: rgba(215,119,119,.08);
  padding: .6rem 1rem; font-size: .9rem; margin: 1rem 0;
}
.toc { background: rgba(127,127,127,.08); padding: .8rem 1rem; border-radius: 6px; }
.toc ul { list-style: none; padding-left: 1rem; margin: .3rem 0; }
.toc li { padding: .15rem 0; }
.toc a { text-decoration: none; }
.toc a:hover { text-decoration: underline; }
details {
  margin: .8rem 0;
  border: 1px solid rgba(127,127,127,.25);
  border-radius: 6px;
  padding: .4rem .8rem;
}
details[open] { background: rgba(127,127,127,.04); }
details > summary {
  cursor: pointer;
  font-weight: 600;
  padding: .3rem 0;
  list-style-position: outside;
}
details > summary > .meta { font-weight: 400; opacity: .65; margin-left: .6rem; font-size: .9rem; }
details > .body { padding: .8rem 0 .4rem; }
details > .body h1:first-of-type { display: none; }   /* dedupe: summary already names the run */
"""

DISCLAIMER_HTML = (
  '<div class="disclaimer"><strong>Disclaimer:</strong> Reports below are '
  'generated by an LLM-based research agent for experimentation. They are '
  '<em>not</em> financial advice. Treat the analysis as a synthetic exercise.'
  '</div>'
)


class Run(NamedTuple):
    ticker: str
    analysis_date: str  # YYYY-MM-DD
    model: str
    run_started: str    # YYYY-MM-DD HH:MM:SS
    folder: Path        # docs/<run-folder>
    anchor: str         # HTML id used by the TOC


def parse_run_folder(path: Path) -> Run | None:
    if not path.is_dir():
        return None
    m = RUN_DIR_RE.match(path.name)
    if not m:
        return None
    date = m.group("date")
    analysis_date = f"{date[:4]}-{date[4:6]}-{date[6:8]}"
    rd, rt = m.group("run_date"), m.group("run_time")
    if rd and rt:
        run_started = f"{rd[:4]}-{rd[4:6]}-{rd[6:8]} {rt[:2]}:{rt[2:4]}:{rt[4:6]}"
    else:
        run_started = datetime.fromtimestamp(path.stat().st_mtime).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    return Run(
        ticker=m.group("ticker").upper(),
        analysis_date=analysis_date,
        model=m.group("model"),
        run_started=run_started,
        folder=path,
        anchor=f"run-{path.name}",
    )


def render_markdown(text: str) -> str:
    if markdown is not None:
        return markdown.markdown(
            text, extensions=["tables", "fenced_code", "toc"]
        )
    return f"<pre>{html.escape(text)}</pre>"


def render_run_block(run: Run) -> str:
    complete = run.folder / "complete_report.md"
    if complete.is_file():
        body_html = render_markdown(complete.read_text(encoding="utf-8"))
    else:
        body_html = "<p><em>complete_report.md missing for this run.</em></p>"

    summary = (
        f"<strong>{html.escape(run.ticker)}</strong> "
        f"<span class='meta'>{html.escape(run.analysis_date)} "
        f"· {html.escape(run.model)} "
        f"· {html.escape(run.run_started)}</span>"
    )
    return (
        f"<details id='{html.escape(run.anchor)}'>\n"
        f"  <summary>{summary}</summary>\n"
        f"  <div class='body'>\n{body_html}\n  </div>\n"
        f"</details>"
    )


def render_toc(by_ticker: dict[str, list[Run]]) -> str:
    parts = ["<nav class='toc'>", "<strong>Tickers</strong>"]
    for ticker in sorted(by_ticker):
        runs = by_ticker[ticker]
        parts.append(f"<ul><li><a href='#ticker-{html.escape(ticker)}'>"
                     f"{html.escape(ticker)}</a> "
                     f"<span class='muted'>({len(runs)})</span><ul>")
        for r in sorted(
            runs, key=lambda r: (r.analysis_date, r.run_started), reverse=True
        ):
            parts.append(
                f"<li><a href='#{html.escape(r.anchor)}'>"
                f"{html.escape(r.analysis_date)} "
                f"<code>{html.escape(r.model)}</code></a></li>"
            )
        parts.append("</ul></li></ul>")
    parts.append("</nav>")
    return "\n".join(parts)


def build_page(runs: list[Run]) -> str:
    by_ticker: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        by_ticker[r.ticker].append(r)

    body = [
        "<h1>TradingAgents Reports</h1>",
        f"<p class='muted'>{len(runs)} runs across {len(by_ticker)} tickers. "
        "Click a run to expand.</p>",
        DISCLAIMER_HTML,
        render_toc(by_ticker),
    ]
    for ticker in sorted(by_ticker):
        body.append(f"<h2 id='ticker-{html.escape(ticker)}'>{html.escape(ticker)}</h2>")
        ticker_runs = sorted(
            by_ticker[ticker],
            key=lambda r: (r.analysis_date, r.run_started),
            reverse=True,
        )
        for r in ticker_runs:
            body.append(render_run_block(r))

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        "<title>TradingAgents Reports</title>\n"
        "<style>" + PAGE_CSS + "</style>\n"
        "</head>\n<body>\n"
        + "\n".join(body)
        + "\n</body>\n</html>\n"
    )


def main() -> int:
    if not DOCS_DIR.is_dir():
        print(f"docs/ not found at {DOCS_DIR}", file=sys.stderr)
        return 1

    (DOCS_DIR / ".nojekyll").touch()

    runs: list[Run] = []
    for child in sorted(DOCS_DIR.iterdir()):
        run = parse_run_folder(child)
        if run is None:
            continue
        runs.append(run)

    if not runs:
        print("No run folders found under docs/.", file=sys.stderr)
        return 1

    (DOCS_DIR / "index.html").write_text(build_page(runs), encoding="utf-8")
    print(f"Built single-page docs/index.html with {len(runs)} runs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
