"""Build a just-the-docs Jekyll site for GitHub Pages from docs/ runs.

Each run lives at ``docs/<TICKER>/<DATE>_<MODEL>_<TS>/complete_report.md``.

Layout produced by this script:

* ``docs/index.md`` -- nav root, latest-decision summary, links to one hub
  page per ticker, and regeneration instructions.
* ``docs/<TICKER>/index.md`` -- per-ticker hub page (nav parent), table of
  runs.
* Each run's ``complete_report.md`` is given just-the-docs front matter
  (``parent: <TICKER>``, ``title: <run-started>``) so it slots into the
  left sidebar under its ticker. Existing front matter is replaced.

Run locally:

    python scripts/build_reports_site.py

Idempotent: rewrites ``docs/index.md``, ``docs/<TICKER>/index.md``, and
the front matter blocks of each ``complete_report.md`` in place.
"""

from __future__ import annotations

import math
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import NamedTuple


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

TICKER_DIR_RE = re.compile(r"^[A-Za-z0-9.\-]+$")

# Run folder name is <DATE>_<MODEL>[_<RUN_DATE>_<RUN_TIME>]. The optional
# RUN_DATE/RUN_TIME tail records when the run started (vs. the analysis
# date). MODEL is non-greedy so it doesn't swallow the trailing timestamp.
RUN_DIR_RE = re.compile(
    r"^(?P<date>\d{8})_(?P<model>.+?)"
    r"(?:_(?P<run_date>\d{8})_(?P<run_time>\d{6}))?$"
)

DISCLAIMER = (
    "> **Disclaimer:** Reports are generated by an LLM-based research "
    "agent for experimentation. They are **not** financial advice. Treat "
    "the analysis as a synthetic exercise."
)

FRONT_MATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)


class Run(NamedTuple):
    ticker: str
    analysis_date: str   # YYYY-MM-DD
    model: str
    run_started: str     # YYYY-MM-DD HH:MM:SS
    folder_name: str     # used in URLs


class SummaryRow(NamedTuple):
    ticker: str
    report_link: str
    rating: str
    action: str
    current_price: float | None
    price_target: float | None
    target_uplift: float | None
    annualized_uplift: float | None
    confidence: str
    horizon: str


def parse_run_folder(ticker_dir: Path, run_path: Path) -> Run | None:
    """Parse ``docs/<TICKER>/<RUN>``; ticker comes from the parent dir."""
    if not run_path.is_dir():
        return None
    m = RUN_DIR_RE.match(run_path.name)
    if not m:
        return None
    date = m.group("date")
    analysis_date = f"{date[:4]}-{date[4:6]}-{date[6:8]}"
    rd, rt = m.group("run_date"), m.group("run_time")
    if rd and rt:
        run_started = f"{rd[:4]}-{rd[4:6]}-{rd[6:8]} {rt[:2]}:{rt[2:4]}:{rt[4:6]}"
    else:
        run_started = datetime.fromtimestamp(run_path.stat().st_mtime).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    return Run(
        ticker=ticker_dir.name.upper(),
        analysis_date=analysis_date,
        model=m.group("model"),
        run_started=run_started,
        folder_name=run_path.name,
    )


def read_text(path: Path) -> str:
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def field(text: str, name: str) -> str:
    m = re.search(rf"^\*\*{re.escape(name)}\*\*:\s*(.+)$", text, flags=re.M)
    return m.group(1).strip() if m else ""


def parse_money(value: str) -> float | None:
    value = value.strip().replace(",", "")
    try:
        return float(value)
    except ValueError:
        return None


CURRENT_PRICE_PATTERNS = [
    r"closed\s+Friday,\s*\*\*\d{4}-\d{2}-\d{2}\s+at\s+\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Most recent close[^$\n]*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Latest close[^$\n]*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Latest trading day[^\n$]*(?:Last close|close)\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"last trading day[^\n$]*close\s+\$([0-9][0-9,]*(?:\.\d+)?)",
    r"\*\*Last Close:\*\*\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Last Close\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"\*\*Last close:\*\*\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Last close\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Current close\s*\([^)]*\)\*{0,2}\s*:?\s*\*{0,2}\$([0-9][0-9,]*(?:\.\d+)?)",
    r"Close\s*\(5/29\)\s*:?\s*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"ending\s+the\s+week\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"(?:close|closing)\s+of\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closed\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closed\s+May\s+29\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"to\s+\$([0-9][0-9,]*(?:\.\d+)?)\s+close\s+on\s+\d{4}-\d{2}-\d{2}",
    r"recent close is\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"May\s+29,\s+\d{4}:\*\*\s+[^\n]*?closing\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29:\*\*\s+[^\n]*?close\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29\)\s+closed\s+at\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"May\s+29\s+close\s+\(\$([0-9][0-9,]*(?:\.\d+)?)\)",
    r"last\s+printing\s+a\s+close\s+of\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-05-29",
    r"5/29\s+\(price\s+down[^$]*\$([0-9][0-9,]*(?:\.\d+)?)\)",
    r"then\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closing\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"closing\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-\d{2}-\d{2}",
    r"closed\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-\d{2}-\d{2}",
    r"closed\s+\$([0-9][0-9,]*(?:\.\d+)?)\s+on\s+\d{4}-\d{2}-\d{2}",
    r"Close\s+rose\s+from[^\n]+?to\s+\*\*\$?([0-9][0-9,]*(?:\.\d+)?)\s+\(May\s+29\)",
    r"Close\s+\$[0-9][0-9,]*(?:\.\d+)?[^\n]+?→\s+\*\*\$([0-9][0-9,]*(?:\.\d+)?)",
    r"closing\s+\*\*([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29",
    r"new\s+high\s+\(([0-9][0-9,]*(?:\.\d+)?)\s+on\s+May\s+29\)",
    r"\|\s*\d{4}-05-29\s*\|\s*\*\*\$([0-9][0-9,]*(?:\.\d+)?)\*\*",
    r"\|\s*Close\s*\|\s*\*?\*?\$([0-9][0-9,]*(?:\.\d+)?)\*?\*?",
]

CURRENT_PRICE_FALLBACK_PATTERNS = [
    r"\bat\s+~\$([0-9][0-9,]*(?:\.\d+)?)\b",
    r"near\s+current\s+~?\$([0-9][0-9,]*(?:\.\d+)?)\b",
    r"current\s+~?\$([0-9][0-9,]*(?:\.\d+)?)\s+(?:strength|level|levels|print)",
]


def extract_current_price(report_text: str, decision_text: str, trader_text: str) -> float | None:
    # Current means the report-time latest close, not a live quote.
    market_text = report_text.split("### Sentiment Analyst", 1)[0]
    for pattern in CURRENT_PRICE_PATTERNS:
        m = re.search(pattern, market_text[:35000], flags=re.I)
        if m:
            return parse_money(m.group(1))
    decision_and_trader = f"{decision_text}\n{trader_text}"
    for pattern in CURRENT_PRICE_FALLBACK_PATTERNS:
        m = re.search(pattern, decision_and_trader, flags=re.I)
        if m:
            return parse_money(m.group(1))
    return parse_money(field(trader_text, "Entry Price"))


def extract_confidence(report_text: str) -> str:
    for pattern in (
        r"^\*\*Confidence:\*\*\s*([A-Za-z]+)",
        r"Confidence is \*\*([A-Za-z]+)\*\*",
        r"Confidence:\s*([A-Za-z]+)",
    ):
        m = re.search(pattern, report_text, flags=re.I | re.M)
        if m:
            return m.group(1).capitalize()
    return "n/a"


def horizon_months(horizon: str) -> float | None:
    h = horizon.lower()
    if "4 quarters" in h:
        return 12.0
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*days?", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) / 30.4375
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*weeks?", h)
    if m:
        return ((float(m.group(1)) + float(m.group(2))) / 2.0) * 12.0 / 52.0
    m = re.search(r"(\d+)\s*-\s*(\d+)\s*months?", h)
    if m:
        return (float(m.group(1)) + float(m.group(2))) / 2.0
    m = re.search(r"(\d+)\s*months?", h)
    if m:
        return float(m.group(1))
    return None


def build_summary_row(run: Run) -> SummaryRow:
    run_dir = DOCS_DIR / run.ticker / run.folder_name
    decision_text = read_text(run_dir / "5_portfolio" / "decision.md")
    trader_text = read_text(run_dir / "3_trading" / "trader.md")
    report_text = read_text(run_dir / "complete_report.md")

    current = extract_current_price(report_text, decision_text, trader_text)
    target = parse_money(field(decision_text, "Price Target"))
    target_uplift = None
    annualized_uplift = None
    if current and target:
        target_uplift = target / current - 1.0
        months = horizon_months(field(decision_text, "Time Horizon"))
        if months and months > 0 and 1.0 + target_uplift > 0:
            annualized_uplift = math.pow(1.0 + target_uplift, 12.0 / months) - 1.0

    return SummaryRow(
        ticker=run.ticker,
        report_link=f"./{run.ticker}/{run.folder_name}/complete_report.html",
        rating=field(decision_text, "Rating") or "n/a",
        action=field(trader_text, "Action") or "n/a",
        current_price=current,
        price_target=target,
        target_uplift=target_uplift,
        annualized_uplift=annualized_uplift,
        confidence=extract_confidence(report_text),
        horizon=field(decision_text, "Time Horizon") or "n/a",
    )


def latest_runs(by_ticker: dict[str, list[Run]]) -> list[Run]:
    runs = []
    for ticker_runs in by_ticker.values():
        runs.append(
            sorted(
                ticker_runs,
                key=lambda r: (r.analysis_date, r.run_started),
                reverse=True,
            )[0]
        )
    return runs


def summary_sort_key(row: SummaryRow) -> tuple[int, float]:
    action_rank = {"Buy": 0, "Hold": 1, "Sell": 2}
    return (
        action_rank.get(row.action, 9),
        -(row.target_uplift if row.target_uplift is not None else -999.0),
    )


def format_price(value: float | None) -> str:
    if value is None:
        return "n/a"
    if value >= 1000:
        return f"${value:,.0f}"
    if value >= 100:
        return f"${value:,.2f}"
    return f"${value:.2f}"


def format_percent(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value * 100:+.1f}%"


def short_horizon(horizon: str) -> str:
    return (
        horizon.replace(" months", "m")
        .replace(" month", "m")
        .replace(" weeks", "w")
        .replace(" week", "w")
        .replace(" days", "d")
        .replace(" day", "d")
    )


def build_decision_summary(rows: list[SummaryRow]) -> list[str]:
    lines = [
        "## Latest Decision Summary",
        "",
        "_Uses the latest run folder for each ticker. Current price is the report-time latest close parsed from the report, not a live quote. Target uplift is target/current. 1Y uplift is annualized from the midpoint of the stated horizon, so short-horizon rows can look extreme._",
        "",
        "| Ticker | Suggestion | Current | Target | Target uplift | 1Y uplift | Confidence | Horizon |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for row in sorted(rows, key=summary_sort_key):
        suggestion = f"{row.action} / {row.rating}"
        lines.append(
            f"| [{row.ticker}]({row.report_link}) | {suggestion} | "
            f"{format_price(row.current_price)} | {format_price(row.price_target)} | "
            f"{format_percent(row.target_uplift)} | {format_percent(row.annualized_uplift)} | "
            f"{row.confidence} | {short_horizon(row.horizon)} |"
        )
    lines.append("")
    return lines


def build_regeneration_skill() -> list[str]:
    return [
        "## Regeneration Skill",
        "",
        "When ticker folders are upgraded with newer report data, regenerate this homepage instead of editing the table by hand:",
        "",
        "1. Add each completed run under `docs/<TICKER>/<YYYYMMDD>_<MODEL>_<YYYYMMDD>_<HHMMSS>/` with `complete_report.md`, `3_trading/trader.md`, and `5_portfolio/decision.md` present.",
        "2. Run `python scripts/build_reports_site.py` from the repository root.",
        "3. Review `docs/index.md` and the affected `docs/<TICKER>/index.md` files in `git diff`.",
        "4. If a row shows `n/a`, check that the new report includes `**Rating**`, `**Price Target**`, `**Time Horizon**`, `**Action**`, and a latest close/current price line in the market report.",
        "",
        "The generator always chooses the newest run per ticker by analysis date and run-start timestamp.",
        "",
    ]


def build_home(
    by_ticker: dict[str, list[Run]], total_runs: int, summary_rows: list[SummaryRow]
) -> str:
    tickers = sorted(by_ticker)
    lines = [
        "---",
        "title: Home",
        "layout: default",
        "nav_order: 1",
        "---",
        "",
        "# TradingAgents Reports",
        "",
        f"_{total_runs} runs across {len(tickers)} tickers._",
        "",
        DISCLAIMER,
        "",
        *build_decision_summary(summary_rows),
        *build_regeneration_skill(),
        "## Tickers",
        "",
    ]
    for ticker in tickers:
        n = len(by_ticker[ticker])
        suffix = "run" if n == 1 else "runs"
        lines.append(f"- [{ticker}](./{ticker}/) &middot; {n} {suffix}")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_ticker_hub(ticker: str, runs: list[Run], nav_order: int) -> str:
    runs_sorted = sorted(
        runs,
        key=lambda r: (r.analysis_date, r.run_started),
        reverse=True,
    )
    lines = [
        "---",
        f"title: {ticker}",
        "layout: default",
        f"nav_order: {nav_order}",
        "has_children: true",
        "---",
        "",
        f"# {ticker}",
        "",
        f"_{len(runs_sorted)} run(s)._",
        "",
        "| Analysis date | Model | Run started | Report |",
        "| --- | --- | --- | --- |",
    ]
    for r in runs_sorted:
        link = f"./{r.folder_name}/complete_report.html"
        lines.append(
            f"| {r.analysis_date} | `{r.model}` | {r.run_started} | "
            f"[Open]({link}) |"
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def report_front_matter(run: Run) -> str:
    return (
        "---\n"
        f'title: "{run.run_started} &middot; {run.model}"\n'
        f"parent: {run.ticker}\n"
        "layout: default\n"
        "---\n"
    )


def write_report_front_matter(run: Run) -> bool:
    """Add or replace the just-the-docs front matter on a run's report.

    Returns True if the file was rewritten.
    """
    path = DOCS_DIR / run.ticker / run.folder_name / "complete_report.md"
    if not path.is_file():
        return False
    body = path.read_text(encoding="utf-8")
    desired = report_front_matter(run)
    existing = FRONT_MATTER_RE.match(body)
    if existing:
        if existing.group(0) == desired:
            return False
        body = body[existing.end():]
    new_body = desired + body
    if new_body == path.read_text(encoding="utf-8"):
        return False
    path.write_text(new_body, encoding="utf-8")
    return True


def main() -> int:
    if not DOCS_DIR.is_dir():
        print(f"docs/ not found at {DOCS_DIR}", file=sys.stderr)
        return 1

    runs: list[Run] = []
    for ticker_dir in sorted(DOCS_DIR.iterdir()):
        if not ticker_dir.is_dir():
            continue
        if not TICKER_DIR_RE.match(ticker_dir.name):
            continue
        if ticker_dir.name == "assets":
            continue
        for run_dir in sorted(ticker_dir.iterdir()):
            run = parse_run_folder(ticker_dir, run_dir)
            if run is None:
                continue
            runs.append(run)

    if not runs:
        print("No run folders found under docs/.", file=sys.stderr)
        return 1

    by_ticker: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        by_ticker[r.ticker].append(r)

    summary_rows = [build_summary_row(r) for r in latest_runs(by_ticker)]

    (DOCS_DIR / "index.md").write_text(
        build_home(by_ticker, total_runs=len(runs), summary_rows=summary_rows),
        encoding="utf-8",
    )

    for nav_order, ticker in enumerate(sorted(by_ticker), start=2):
        hub_path = DOCS_DIR / ticker / "index.md"
        hub_path.parent.mkdir(parents=True, exist_ok=True)
        hub_path.write_text(
            build_ticker_hub(ticker, by_ticker[ticker], nav_order),
            encoding="utf-8",
        )

    rewritten = 0
    for r in runs:
        if write_report_front_matter(r):
            rewritten += 1

    print(
        f"Wrote docs/index.md, {len(by_ticker)} ticker hubs, and updated "
        f"front matter on {rewritten} of {len(runs)} run reports."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
