#!/usr/bin/env bash
# Generate a test hLedger journal with three platforms for dashboard development.
#
# Platforms: test, degiro, ibkr
# Includes edge cases: delisted ticker, zero-quantity, crypto, multi-currency cash.
#
# Usage:
#   ./scripts/seed_test_journal.sh                     → write to default location
#   ./scripts/seed_test_journal.sh /tmp/test.journal   → write to custom path
#
# Then point the dashboard at it:
#   HLEDGER_FILE=/tmp/test.journal bun run server/index.tsx
#
# Or use the just recipe:
#   just seed-test-journal

set -euo pipefail

OUTPUT="${1:-${HOME}/.hledger.journal}"
BACKUP="${OUTPUT}.bak.$(date +%Y%m%d_%H%M%S)"

echo "=== hLedger Test Journal Generator ==="

# Back up existing journal if it exists
if [ -f "$OUTPUT" ] && [ -s "$OUTPUT" ]; then
  cp "$OUTPUT" "$BACKUP"
  echo "Backed up existing journal to: $BACKUP"
fi

cat > "$OUTPUT" << 'HLEDGER_EOF'
; ── TradingAgents Test Journal ────────────────────────────────────
; Generated by scripts/seed_test_journal.sh
;
; Account convention: assets:<platform>:<account_type>
;   Platform examples: degiero, ibkr, pension:nn, test
;
; Commodities with dots (TKA.DE, VWCE.DE) must be quoted.
; Prices are synthetic — for UI testing only, not trading signals.

; ── Prices (last 30 days) ─────────────────────────────────────────

P 2026-04-03 "TKA.DE"    8.20 EUR
P 2026-04-10 "TKA.DE"    8.45 EUR
P 2026-04-17 "TKA.DE"    8.60 EUR
P 2026-04-24 "TKA.DE"    8.35 EUR
P 2026-05-01 "TKA.DE"    8.50 EUR

P 2026-04-03 "VWCE.DE"  132.00 EUR
P 2026-04-10 "VWCE.DE"  134.50 EUR
P 2026-04-17 "VWCE.DE"  136.20 EUR
P 2026-04-24 "VWCE.DE"  135.80 EUR
P 2026-05-01 "VWCE.DE"  137.00 EUR

P 2026-04-03 "AAPL"     188.50 USD
P 2026-04-10 "AAPL"     192.00 USD
P 2026-04-17 "AAPL"     195.00 USD
P 2026-04-24 "AAPL"     190.00 USD
P 2026-05-01 "AAPL"     194.00 USD

P 2026-04-03 "MSFT"     448.00 USD
P 2026-04-10 "MSFT"     452.00 USD
P 2026-04-17 "MSFT"     458.00 USD
P 2026-04-24 "MSFT"     455.00 USD
P 2026-05-01 "MSFT"     460.00 USD

P 2026-04-03 "BTC"    68000.00 USD
P 2026-04-10 "BTC"    71000.00 USD
P 2026-04-17 "BTC"    73000.00 USD
P 2026-04-24 "BTC"    70000.00 USD
P 2026-05-01 "BTC"    72000.00 USD

P 2026-04-03 "DELISTED" 5.00 EUR
P 2026-04-10 "DELISTED" 4.80 EUR
P 2026-04-17 "DELISTED" 4.50 EUR
P 2026-04-24 "DELISTED" 3.00 EUR

; ── Platform: test ────────────────────────────────────────────────
; Small test account with edge cases

2026-04-01 * "Open test account"
  assets:test:cash         10,000.00 EUR
  equity:opening

2026-04-05 * "Buy TKA.DE — regular stock"
  assets:test:holdings     500 "TKA.DE"
  assets:test:cash        -4,250.00 EUR

2026-04-10 * "Buy VWCE.DE — ETF"
  assets:test:holdings      10 "VWCE.DE"
  assets:test:cash        -1,345.00 EUR

2026-04-15 * "Buy DELISTED — edge case (delisted ticker)"
  assets:test:holdings     100 "DELISTED"
  assets:test:cash          -500.00 EUR

2026-04-20 * "Buy BTC — crypto holding"
  assets:test:holdings       0.05 "BTC"
  assets:test:cash        -3,550.00 USD

2026-05-01 * "Sell zero-quantity test"
  assets:test:holdings       0 "DELISTED"
  assets:test:cash             0 EUR

; ── Platform: degiero ─────────────────────────────────────────────
; Medium-size active trading account

2026-04-01 * "Open degiero account"
  assets:degiero:cash       25,000.00 EUR
  equity:opening

2026-04-05 * "Buy AAPL — large position"
  assets:degiero:holdings     80 "AAPL"
  assets:degiero:cash     -15,520.00 USD

2026-04-10 * "Buy MSFT — second position"
  assets:degiero:holdings     30 "MSFT"
  assets:degiero:cash     -13,560.00 USD

2026-04-15 * "Buy VWCE.DE — ETF allocation"
  assets:degiero:holdings     50 "VWCE.DE"
  assets:degiero:cash       -6,790.00 EUR

2026-04-20 * "Buy BTC — speculative"
  assets:degiero:holdings     0.1 "BTC"
  assets:degiero:cash       -7,300.00 USD

; ── Platform: ibkr ────────────────────────────────────────────────
; Large diversified account (violates some governance rules)

2026-04-01 * "Open ibkr account"
  assets:ibkr:cash          50,000.00 EUR
  equity:opening

2026-04-05 * "Buy AAPL — overweight position"
  assets:ibkr:holdings       150 "AAPL"
  assets:ibkr:cash        -28,275.00 USD

2026-04-10 * "Buy MSFT"
  assets:ibkr:holdings        60 "MSFT"
  assets:ibkr:cash        -27,480.00 USD

2026-04-15 * "Buy VWCE.DE — core holding"
  assets:ibkr:holdings       100 "VWCE.DE"
  assets:ibkr:cash         -13,580.00 EUR

2026-04-20 * "Cash withdrawal test"
  assets:ibkr:cash           -2,000.00 EUR
  expenses:test-withdrawal

2026-04-25 * "Buy TKA.DE — small cap exposure"
  assets:ibkr:holdings      1000 "TKA.DE"
  assets:ibkr:cash           -8,600.00 EUR

; ── Cross-platform transfer test ──────────────────────────────────
2026-04-30 * "Transfer from degiero to ibkr"
  assets:degiero:cash        -5,000.00 EUR
  assets:ibkr:cash            5,000.00 EUR

HLEDGER_EOF

echo "Wrote test journal to: $OUTPUT"
echo ""

# Show summary
hledger -f "$OUTPUT" balance --tree --value end 2>/dev/null || {
  echo "⚠️  hledger not found — install it to verify the journal: brew install hledger"
}

echo ""
echo "Done. To use this journal with the dashboard:"
echo "  HLEDGER_FILE=$OUTPUT bun run server/index.tsx"
echo ""
echo "Platforms: test (3 edge cases), degiero (4 holdings), ibkr (4 holdings)"
echo "Edge cases: delisted ticker (DELISTED), zero-quantity, crypto, multi-currency"
