#!/usr/bin/env bun

/**
 * Research bridge — run TradingAgents analysis and extract buylist values.
 *
 * Runs the Python multi-agent pipeline, then parses the saved state JSON
 * for entry_price, stop_loss, position_sizing, and price_target.
 * Optionally writes extracted values to the watchlist table.
 *
 * Usage:
 *   trading research AAPL              # run analysis, show summary
 *   trading research AAPL --write      # write entry_price → fair_value
 *   trading research AAPL --fetch      # update price after analysis
 */

import { existsSync } from "node:fs"
import { join } from "node:path"
import { DatabaseFactory } from "@lib/db"
import { cfg } from "@lib/settings"
import { defineCommand } from "citty"
import { gum } from "../../../scripts/lib/gum.ts"

interface ParsedState {
  entryPrice: number | null
  stopLoss: number | null
  positionSizing: string | null
  priceTarget: number | null
  rating: string | null
  action: string | null
}

async function findLatestStateFile(ticker: string): Promise<string | null> {
  const home = process.env.HOME ?? "~"
  const dir = join(home, ".tradingagents", "logs", ticker, "TradingAgentsStrategy_logs")
  if (!existsSync(dir)) return null

  // Find newest full_states_log_*.json
  const proc = Bun.spawn({
    cmd: ["bash", "-c", `ls -t "${dir}"/full_states_log_*.json | head -1`],
    stdout: "pipe",
    stderr: "pipe",
  })

  const path = (await new Response(proc.stdout).text()).trim()
  return path && existsSync(path) ? path : null
}

function parseState(path: string): ParsedState {
  try {
    const content = require("node:fs").readFileSync(path, "utf-8")
    const state = JSON.parse(content)

    const traderPlan: string = state.trader_investment_decision ?? ""
    const finalDecision: string = state.final_trade_decision ?? ""

    const entryMatch = traderPlan.match(/\*\*Entry Price\*\*:\s*([\d.]+)/)
    const stopMatch = traderPlan.match(/\*\*Stop Loss\*\*:\s*([\d.]+)/)
    const sizingMatch = traderPlan.match(/\*\*Position Sizing\*\*:\s*(.+?)(?:\n\n|\nFINAL)/s)
    const targetMatch = finalDecision.match(/\*\*Price Target\*\*:\s*([\d.]+)/)
    const ratingMatch = finalDecision.match(/\*\*Rating\*\*:\s*(\w+)/)
    const actionMatch = traderPlan.match(/\*\*Action\*\*:\s*(\w+)/)

    return {
      entryPrice: entryMatch ? parseFloat(entryMatch[1]) : null,
      stopLoss: stopMatch ? parseFloat(stopMatch[1]) : null,
      positionSizing: sizingMatch ? sizingMatch[1].trim() : null,
      priceTarget: targetMatch ? parseFloat(targetMatch[1]) : null,
      rating: ratingMatch ? ratingMatch[1] : null,
      action: actionMatch ? actionMatch[1] : null,
    }
  } catch {
    return {
      entryPrice: null,
      stopLoss: null,
      positionSizing: null,
      priceTarget: null,
      rating: null,
      action: null,
    }
  }
}

function latestPrice(db: ReturnType<typeof DatabaseFactory.get>, ticker: string): number | null {
  const row = db
    .query<{ close: number }, [string]>(
      "SELECT close FROM prices WHERE ticker = ? ORDER BY date DESC LIMIT 1",
    )
    .get(ticker)
  return row ? row.close : null
}

async function fetchPrice(ticker: string): Promise<number | null> {
  try {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "scripts/get_price.ts", ticker],
      stdout: "pipe",
      stderr: "pipe",
    })
    const text = await new Response(proc.stdout).text()
    const data = JSON.parse(text)
    return data.price ?? null
  } catch {
    return null
  }
}

// ── Display ────────────────────────────────────────────────────────────────

async function displayResult(ticker: string, parsed: ParsedState, currentPrice: number | null) {
  const title = await gum(`${ticker} — Research Bridge`, ["--bold", "--foreground", "212"])
  console.log(`  ${title}`)

  const lines = [`${"Field".padEnd(18)} ${"Value"}`, "─".repeat(50)]

  const addLine = (label: string, value: string | null) => {
    const display = value ?? "\x1b[90m(not generated by pipeline)\x1b[0m"
    lines.push(`${label.padEnd(18)} ${display}`)
  }

  addLine("Action", parsed.action)
  addLine("Rating", parsed.rating)
  addLine("Entry Price", parsed.entryPrice != null ? `£${parsed.entryPrice.toFixed(2)}` : null)
  addLine("Stop Loss", parsed.stopLoss != null ? `£${parsed.stopLoss.toFixed(2)}` : null)
  addLine("Price Target", parsed.priceTarget != null ? `£${parsed.priceTarget.toFixed(2)}` : null)
  addLine("Position Sizing", parsed.positionSizing)
  addLine("Current Price", currentPrice != null ? `£${currentPrice.toFixed(2)}` : null)

  const box = await gum(lines.join("\n"), ["--border", "rounded", "--padding", "1 2"])
  console.log(box)

  if (parsed.entryPrice != null && currentPrice != null) {
    const gap = ((currentPrice - parsed.entryPrice) / parsed.entryPrice) * 100
    const colour = currentPrice <= parsed.entryPrice ? "\x1b[32m" : "\x1b[0m"
    console.log(`  ${colour}Gap to entry: ${gap >= 0 ? "+" : ""}${gap.toFixed(1)}%${"\x1b[0m"}`)
  }

  console.log("")
}

// ── Command ────────────────────────────────────────────────────────────────

export const researchCommand = defineCommand({
  meta: {
    name: "research",
    description: "Run TradingAgents analysis and extract buylist values",
  },
  args: {
    ticker: {
      type: "positional",
      description: "Stock ticker to research (e.g. AAPL, TKA.DE)",
      required: true,
    },
    write: {
      type: "boolean",
      description: "Write entry_price to watchlist.fair_value",
      default: false,
    },
    fetch: {
      type: "boolean",
      description: "Fetch current price after analysis",
      default: false,
    },
    debates: {
      type: "string",
      description: "Number of debate rounds",
      default: "1",
    },
  },
  run: async ({ args }) => {
    const ticker = args.ticker
    const script = join(process.cwd(), "scripts", "py", "analyze_stream.py")

    if (!existsSync(script)) {
      console.error(`Error: analyze_stream.py not found at ${script}`)
      process.exit(1)
    }

    console.log(`Running TradingAgents analysis for ${ticker}...`)
    console.log("(This may take 2-5 minutes depending on LLM provider)")
    console.log("")

    // Run the Python pipeline
    const env = { ...process.env, PYTHONUNBUFFERED: "1" }
    const proc = Bun.spawn(["python3", script, ticker, "--debates", args.debates], {
      stdout: "inherit",
      stderr: "inherit",
      env,
    })

    const exitCode = await proc.exited
    if (exitCode !== 0) {
      console.error(`\nAnalysis failed with exit code ${exitCode}`)
      process.exit(exitCode)
    }

    console.log("")
    console.log("Analysis complete. Parsing state...")
    console.log("")

    // Find and parse the latest state file
    const statePath = await findLatestStateFile(ticker)
    if (!statePath) {
      console.error(`No state file found for ${ticker} in ~/.tradingagents/logs/`)
      process.exit(1)
    }

    const parsed = parseState(statePath)

    // Get current price
    DatabaseFactory.connect(cfg.portfolio.db)
    const db = DatabaseFactory.get()
    let currentPrice = latestPrice(db, ticker)
    if (currentPrice == null && args.fetch) {
      currentPrice = await fetchPrice(ticker)
    }

    // Display results
    await displayResult(ticker, parsed, currentPrice)

    // Write to watchlist if requested
    if (args.write) {
      if (parsed.entryPrice == null) {
        console.log("  ⚠ No entry_price found in analysis. Nothing written to watchlist.")
        console.log("  The pipeline did not generate a specific entry price for this ticker.")
        return
      }

      // Check if ticker exists in watchlist
      const existing = db
        .query<{ id: number }, [string]>("SELECT id FROM watchlist WHERE ticker = ?")
        .get(ticker)

      if (existing) {
        db.run("UPDATE watchlist SET fair_value = ?, max_position_gbp = ? WHERE ticker = ?", [
          parsed.entryPrice,
          null,
          ticker,
        ])
        console.log(
          `  ✓ Updated watchlist: ${ticker} fair_value = £${parsed.entryPrice.toFixed(2)}`,
        )
      } else {
        db.run(
          "INSERT INTO watchlist (ticker, exchange, platform, priority, stage, added_date, thesis, fair_value) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
          [
            ticker,
            "US",
            "unknown",
            "medium",
            "analyzed",
            new Date().toISOString().slice(0, 10),
            "From pipeline research",
            parsed.entryPrice,
          ],
        )
        console.log(
          `  ✓ Added to watchlist: ${ticker} fair_value = £${parsed.entryPrice.toFixed(2)}`,
        )
      }

      if (parsed.positionSizing) {
        console.log(`  ℹ Position sizing suggestion: ${parsed.positionSizing}`)
      }

      console.log("")
      console.log("  Run `trading buylist` to see all contingency items.")
    }
  },
})
