from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


class StateKeys:
    """Type-safe string constants for AgentState dict access.

    Use these instead of raw string literals to prevent typos and enable
    IDE autocomplete / refactoring across the codebase.

    Example::

        # Before (fragile):
        report = state["market_report"]

        # After (safe):
        from tradingagents.agents.utils.agent_states import StateKeys
        report = state[StateKeys.MARKET_REPORT]
    """

    # ── Core inputs ────────────────────────────────────────────────────────
    COMPANY = "company_of_interest"
    ASSET_TYPE = "asset_type"
    TRADE_DATE = "trade_date"
    SENDER = "sender"
    PAST_CONTEXT = "past_context"

    # ── Analyst reports ────────────────────────────────────────────────────
    MARKET_REPORT = "market_report"
    SENTIMENT_REPORT = "sentiment_report"
    NEWS_REPORT = "news_report"
    FUNDAMENTALS_REPORT = "fundamentals_report"
    MACRO_REPORT = "macro_report"
    OPTIONS_REPORT = "options_report"
    QUANT_REPORT = "quant_report"
    EARNINGS_REPORT = "earnings_report"
    REVIEW_REPORT = "review_report"

    # ── Decision chain ─────────────────────────────────────────────────────
    INVESTMENT_DEBATE_STATE = "investment_debate_state"
    INVESTMENT_PLAN = "investment_plan"
    TRADER_INVESTMENT_PLAN = "trader_investment_plan"
    RISK_DEBATE_STATE = "risk_debate_state"
    FINAL_TRADE_DECISION = "final_trade_decision"

    # ── Convenience collections ────────────────────────────────────────────
    #: All report keys in pipeline order — used by WebSocket streaming and
    #: PropagateResult serialisation.
    ALL_REPORT_KEYS: tuple[str, ...] = (
        MARKET_REPORT,
        SENTIMENT_REPORT,
        NEWS_REPORT,
        FUNDAMENTALS_REPORT,
        MACRO_REPORT,
        OPTIONS_REPORT,
        QUANT_REPORT,
        EARNINGS_REPORT,
        REVIEW_REPORT,
        INVESTMENT_PLAN,
        TRADER_INVESTMENT_PLAN,
        FINAL_TRADE_DECISION,
    )


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    macro_report: Annotated[str, "Report from the Macro Analyst"]
    options_report: Annotated[str, "Report from the Options Analyst"]
    quant_report: Annotated[str, "Report from the Quant Analyst"]
    earnings_report: Annotated[str, "Report from the Earnings Analyst"]
    review_report: Annotated[str, "Report from the Performance Review Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
