import re
import uuid
import datetime
from typing import Any, Dict, Optional

from tradingagents.agents.utils.rating import parse_rating

from api.config import TICKER_NAMES
from api.database import get_live_price, validate_price
from api.models import SignalPayload


def parse_markdown_fields(text: str) -> Dict[str, str]:
    """Extract **Key**: value pairs from agent markdown output."""
    fields: Dict[str, str] = {}
    current_key = None
    current_value: list[str] = []

    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        m = re.match(r"\*\*([^*]+)\*\*:\s*(.*)", line)
        if m:
            if current_key:
                fields[current_key] = "\n".join(current_value).strip()
            current_key = m.group(1).strip().lower().replace(" ", "_")
            val = m.group(2).strip()
            current_value = [val] if val else []
        elif current_key:
            current_value.append(line)

    if current_key:
        fields[current_key] = "\n".join(current_value).strip()
    return fields


def _extract_sentiment(text: str) -> tuple[Optional[str], Optional[float]]:
    """Parse band and score from SentimentReport header line."""
    m = re.search(
        r"\*\*Overall Sentiment:\*\*\s+\*\*([^*]+)\*\*.*?Score:\s*([\d.]+)",
        text,
    )
    if m:
        try:
            return m.group(1).strip(), float(m.group(2))
        except Exception:
            return m.group(1).strip(), None
    return None, None


def _vote_from_keywords(text: str, default_vote: str) -> tuple[str, int]:
    t = text.lower()
    bull = sum(
        t.count(w)
        for w in ["bullish", "buy", "overweight", "upside", "positive", "outperform"]
    )
    bear = sum(
        t.count(w)
        for w in [
            "bearish",
            "sell",
            "underweight",
            "downside",
            "negative",
            "underperform",
        ]
    )
    if bull > bear:
        return "bullish", min(90, 50 + bull * 5)
    if bear > bull:
        return "bearish", min(90, 50 + bear * 5)
    return default_vote, 50


def _compute_rr(
    signal_type: str,
    entry: Optional[float],
    target: Optional[float],
    stop: Optional[float],
) -> Optional[float]:
    if None in (entry, target, stop):
        return None
    if signal_type in ("buy", "overweight"):
        denom = entry - stop
        return round((target - entry) / denom, 2) if denom > 0 else None
    if signal_type in ("sell", "underweight"):
        denom = stop - entry
        return round((entry - target) / denom, 2) if denom > 0 else None
    return None


def _compute_grade(confidence: float) -> str:
    if confidence >= 0.85:
        return "A"
    if confidence >= 0.70:
        return "B"
    if confidence >= 0.55:
        return "C"
    return "D"


def normalize_signal(
    ticker: str, asset_type: str, final_state: Dict[str, Any]
) -> Dict[str, Any]:
    pm_text = final_state.get("final_trade_decision", "")
    trader_text = final_state.get("trader_investment_plan", "")
    sentiment_report = final_state.get("sentiment_report", "")
    market_report = final_state.get("market_report", "")
    fundamentals_report = final_state.get("fundamentals_report", "")
    risk_debate = final_state.get("risk_debate_state", {})
    risk_judge = (
        risk_debate.get("judge_decision", "") if isinstance(risk_debate, dict) else ""
    )

    rating = parse_rating(pm_text).lower()
    pm_fields = parse_markdown_fields(pm_text)
    trader_fields = parse_markdown_fields(trader_text)
    live_price = get_live_price(ticker, asset_type)

    def _extract_price(fields: Dict, key: str) -> Optional[float]:
        raw = fields.get(key)
        if not raw:
            return None
        try:
            return validate_price(float(re.findall(r"[\d\.]+", raw)[0]), live_price)
        except Exception:
            return None

    price_target = _extract_price(pm_fields, "price_target")
    entry_price = _extract_price(trader_fields, "entry_price")
    stop_loss = _extract_price(trader_fields, "stop_loss")

    if entry_price is None and live_price is not None:
        entry_price = round(live_price, 2)

    reasoning_summary = (
        pm_fields.get("executive_summary")
        or pm_fields.get("investment_thesis")
        or "Thesis generated by Portfolio Manager."
    )

    # Confidence: rating decisiveness + PM/Trader alignment
    base = {"buy": 0.8, "sell": 0.8, "overweight": 0.6, "underweight": 0.6}.get(
        rating, 0.4
    )
    trader_action = trader_fields.get("action", "").lower()
    aligned = (
        (rating in ("buy", "overweight") and trader_action == "buy")
        or (rating in ("sell", "underweight") and trader_action == "sell")
        or (rating == "hold" and trader_action == "hold")
    )
    confidence = min(0.98, max(0.1, base + (0.15 if aligned else 0.0)))

    sentiment_band, sentiment_score = _extract_sentiment(sentiment_report)

    default_vote = (
        "bullish"
        if rating in ("buy", "overweight")
        else ("bearish" if rating in ("sell", "underweight") else "neutral")
    )
    agent_votes = {
        "fundamental": dict(
            zip(
                ("vote", "score"),
                _vote_from_keywords(fundamentals_report, default_vote),
            )
        ),
        "technical": dict(
            zip(("vote", "score"), _vote_from_keywords(market_report, default_vote))
        ),
        "sentiment": {
            "vote": (
                "bullish"
                if sentiment_band and "bullish" in sentiment_band.lower()
                else "bearish"
                if sentiment_band and "bearish" in sentiment_band.lower()
                else default_vote
            ),
            "score": round((sentiment_score / 10) * 100) if sentiment_score else 50,
        },
        "risk": dict(
            zip(("vote", "score"), _vote_from_keywords(risk_judge, default_vote))
        ),
    }

    inv_debate = final_state.get("investment_debate_state", {})
    inv_debate_text = (
        inv_debate.get("bull_argument", "") + "\n" + inv_debate.get("bear_argument", "")
        if isinstance(inv_debate, dict)
        else str(inv_debate)
    )

    display_ticker = ticker.upper().replace("-USD", "")
    return {
        "id": str(uuid.uuid4()),
        "ticker": ticker.upper(),
        "asset_type": asset_type.lower(),
        "name": TICKER_NAMES.get(display_ticker, display_ticker),
        "signal_type": rating,
        "confidence": round(confidence, 2),
        "time_horizon": pm_fields.get("time_horizon"),
        "price_target": price_target,
        "entry_price": entry_price,
        "stop_loss": stop_loss,
        "position_sizing": trader_fields.get("position_sizing"),
        "reasoning_summary": reasoning_summary,
        "generated_at": datetime.datetime.now(),
        "source_run_id": str(uuid.uuid4()),
        "grade": _compute_grade(confidence),
        "rr": _compute_rr(rating, entry_price, price_target, stop_loss),
        "agent_votes": agent_votes,
        "sentiment_score": sentiment_score,
        "sentiment_band": sentiment_band,
        "market_report": final_state.get("market_report"),
        "news_report": final_state.get("news_report"),
        "fundamentals_report": final_state.get("fundamentals_report"),
        "sentiment_report": sentiment_report or None,
        "pm_report": pm_text or None,
        "trader_report": trader_text or None,
        "investment_debate": inv_debate_text or None,
        "risk_debate": risk_judge or None,
    }


def mask_signal(signal: SignalPayload) -> SignalPayload:
    return SignalPayload(
        id=signal.id,
        ticker=signal.ticker,
        asset_type=signal.asset_type,
        name=signal.name,
        signal_type="locked",
        confidence=0.0,
        time_horizon="Locked",
        price_target=None,
        entry_price=None,
        stop_loss=None,
        position_sizing="Locked",
        reasoning_summary="Upgrade to Pro to view this trading signal.",
        generated_at=signal.generated_at,
        source_run_id=None,
        grade=None,
        rr=None,
        agent_votes=None,
        sentiment_score=None,
        sentiment_band=None,
        market_report=None,
        news_report=None,
        fundamentals_report=None,
        sentiment_report=None,
        pm_report=None,
        trader_report=None,
        investment_debate=None,
        risk_debate=None,
    )
